- guides/oathkeeper/1-overview/1-rules.md
It doesn't make sense to say "if b can handle this, then 'a' and 'b' will be ignored".
> Oathkeeper: Fix typo in rules documentation

- guides/oathkeeper/1-overview/1-rules.md
Docs for the new `headers` credentials issuer.
> oathkeeper: new headers credentials issuer

- guides/hydra/1-tutorial/README.md
I was  confused with an error message when I connected from a public client (AppAuth-JS example).
I needed to add `--token-endpoint-auth-method none`.
> add --token-endpoint-auth-method if public clients

- docs/hydra/configure-deploy.md
I went through the examples given in the configure-deploy chapter and found an environment variable name error causing the `HYDRA_ADMIN_URL` cannot be correctly set in login-consent app, resulting a null property error in the consent app when testing the OAuth2 flow out.
> Fixed configure-deploy document error & typo

- docs/oathkeeper/api-access-rules.md
Please update the documentation for the jwt handler to reflect the change in the naming from `authenticators[].config.require_audience` to `authenticators[].config.target_audience` as the go handler expects `target_audience`. 
Referencing https://github.com/ory/oathkeeper/blob/master/proxy/authenticator_jwt.go Line 32.
> `require_audience` has changed to `target_audience`

- docs/hydra/5min-tutorial.md
Replace over-complicated and error prone `docker ps -f name=hydra_hydra_1 -q` exec intructions (that could also cause name collisions) for integrated docker-compose exec functionality: `docker-compose exec hydra`.
> 5min-tutorial: update docker exec instructions

- docs/hydra/5min-tutorial.md
Update the instructions to use the newly added bash script instead of running manually the docker-compose command to start up the containers. Added an additional example for mysql+tracing.
> 5min-tutorial: update the instructions to use the newly added script

- website/siteConfig.js
I noticed that the forum link is sometimes broken on the site. 'community' works and is spelled correctly but 'comunity' is broken and misspelled. Hopefully fixing this spelling will also fix the broken link.
> update siteConfig.js to fix spelling error + broken link

- docs/keto/index.md
Also changed Role Based Access Control to Role-based Access Control (Wikipedia's spelling).
> fix(keto): Change Wikipedia link to English

- website/static/images/docs/oathkeeper/pipeline.svg
The SVG looks broken on https://www.ory.sh/docs/oathkeeper/#decision-engine. Hopefully, this fresh export without any changes fixes it? Is there a staging server for documentation to test this out?
> Re-export pipeline diagram from Mermaid 8.0.0

- docs/oathkeeper/pipeline/authn.md
Added some documentation for the feature proposed in https://github.com/ory/oathkeeper/pull/211.
Let me know if you think there should be any changes
Thanks!
> Add `cookie_session` documentation

- docs/hydra/dependencies-environment.md
Looks like the docker-compose.yml is renamed and split into multiple files. Linking to the appropriate file.
> Update link to renamed docker-compose file

- docs/hydra/5min-tutorial.md
- docs/hydra/index.md
- docs/hydra/install.md
- docs/performance/hydra.md
I reorganized the OAuth2 and OpenID Connect introductions a bit. This topic is so complex that I think there should be two parts:
1. a very simple (idiot-proof) and short explanation of what OAuth is, to prove that we can understand it so well that we can summarize it properly for non-experts. 
2. a detailed discussion of the various parts of the OAuth spec and how Hydra satisfies and implements them, to prove that we understand all the details of it.
I think the intro in `/docs/hydra/index.md` is a good part for (1). Hence I reformat it in this PR. The structure is now:
- our summary of what OAuth 2.0 is
- our summary of what OpenID Connect is
- links to external videos and articles to learn more details if needed
What do you think?
> Improve Hydra docs

- apis/oathkeeper.json
- docs/oathkeeper/api-access-rules.md
- docs/oathkeeper/configure-deploy.md
- docs/oathkeeper/index.md
- docs/oathkeeper/pipeline/authn.md
- docs/oathkeeper/pipeline/authz.md
- docs/oathkeeper/pipeline/mutator.md
- docs/oathkeeper/sdk/api.md
update documentation to reflect changes implemented in https://github.com/ory/oathkeeper/pull/233
> Support multiple mutation handlers: update documentation

- docs/oathkeeper/pipeline/mutator.md
Document changes introduced in ory/oathkeeper#243
> Update docu: extend-id-token-mutator

- docs/oathkeeper/pipeline/authn.md
Changes proposed in this PR:
* update oauth2_introspection and jwt authenticators documentation with information about setting alternative token location
related PR in Oathkeeper: https://github.com/ory/oathkeeper/pull/271
related Issue: https://github.com/ory/oathkeeper/issues/257
> oathkeeper: update authenticators documentation

- docs/hydra/oauth2.md
- docs/hydra/production.md
Clarify the situation of the Token Introspection endpoint requiring authentication but having no access-control.
[Related forum discussion](https://community.ory.sh/t/token-introspection-not-working/1330)
> Clarify Token Instrospection endpoint

- docs/oathkeeper/pipeline/authn.md
- schemas/oathkeeper.config.schema.json
oathkeeper: add missing "token_from->cookie" documentation for jwt authenticator (#243)
Signed-off-by: Grigoriev, Nikolai <ngrigoriev@gmail.com>
> oathkeeper: add missing "token_from->cookie" documentation for jwt authenticator (#243)

- docs/hydra/production.md
I try to make a production environment and find that I cannot access a logout endpoint from public internet.
Should I not allow to access this logout endpoint from the internet?
> Update production.md to add a logout endpoint.

- docs/kratos/quickstart.md
Fixed spelling error in the Quickstart for Kratos, one too many "the".
> fix: Spelling error for Kratos

- docs/oathkeeper/pipeline/authz.md
This documents a new authorizer called remote_json. Please see https://github.com/ory/oathkeeper/pull/389 for details.
> docs(oathkeeper): Document remote_json authorizer

- docs/ecosystem/sqa.md
- markdown: one instance of normalizing list syntax (first item in list was
numbered, but rest of list items were unordered)
- prose: use "SHA-256" everywhere (rather than sometimes saying "sha256")
- prose: change one instance of "ip addresses" to "IP addresses" (for
consistency with usage elsewhere in the article)
- prose: use "UUID" rather than "uuid" (for consistency -- most acronyms in
article are in all caps)
- prose: restate: "We built this pipeline the data with the following goals:"
as: "We built this pipeline with the following goals in mind:"
> docs: sqa.md: minor content, markdown tweaks

- docs/ecosystem/community.md
Missing Links that arise here might have to do with [this issue](https://github.com/ory/docusaurus-template/issues/31) from ory / docusaurus-template - added in the correct links for now.
> docs: fix community links

- docs/sidebar.json
Added the ecosystem or github inner workings documentation to the sidebar, it was just sitting there in the docs, all forgotten...
> docs: add general contributing to sidebar

- docs/docs/ecosystem/api-design.md
Issue `#2267`: Document that there is an upper bound on `limit` parameter to prevent DoS
> Issue 2267 update doc on limit param upper bound

- docs/docs/ecosystem/community.md
Added a community project and removed @k9ert project (for now).
@aeneasr do you have any input on how we could integrate this page into ory/works? 
We could just link it, but imo would be nice to have all that info directly in the ory/works readme too.. 
I could append it, like we do with ADOPTERS.md in the other readmes, what do you think of that approach?
> docs: add project

- docs/docs/ecosystem/database.md
- docs/docs/ecosystem/deployment.md
This PR adds the documentation for the `max_conn_idle_time` sql flag
This PR is linked to ory/keto#523
> feat: add max_conn_idle_time docs

- docs/docs/ecosystem/projects.md
The order of the service list is not matching the details in the text. This can be confusing for people who approach this page for the first time.
> docs: reorder services list to match the text

- docs/docs/start-building/server-side-web-app.mdx
The command doesn't work with capitalized P and I also get `Error: accepts 1 arg(s), received 3`
for `ory proxy local \  --port 4000 \  http://localhost:8000/`
It works with `ory proxy local --port 4000 http://localhost:8000/`
> fix: proxy command

- docs/docs/start-building/native-mobile-app.mdx
The current list of technologies are used for single page apps
> fix: putting proper list for native and mobile app in native-mobile-app.mdx

- docs/docs/concepts/terminology.mdx
- docs/docs/guides/proxy.mdx
closes https://github.com/ory-corp/cloud/issues/1684
- adds ORY_SDK_URL to terminology doc
- puts Ory specific terms at the top of said doc
- removes ory proxy local as the command is no longer working
- shortens headings from "Ory Proxy for Local Development" to "Local Development", looks cleaner, and should be clear from the heading that it concerns ory proxy. 
optional can be reverted:
- removes the articles, "The Ory Proxy" -> "Ory Proxy", which makes it sound like a proper product. if merged, will remove other articles as well.
> fix: cloud proxy docs

- docs/docs/ecosystem/configuring.md
Closes https://github.com/ory/kratos/issues/1535
Closes https://github.com/ory/kratos/issues/1792
Closes https://github.com/ory/kratos/issues/1801
> docs: clarify configuration

- docs/docs/start-building/server-side-web-app.mdx
The documentation on start-building describes the user should create a PAT token, leading them to be confused when it is not used anywhere in the guide.
> fix: incorrect pat usage

- docs/docs/ecosystem/bugbounty.md
- docs/docs/ecosystem/security.md
- docs/sidebar.json
Adds the bug bounty document to the OS ecosystem documentation. 
We can point to it at an appropriate place in cloud docs. 
When we have the platform for payouts ready we can point to it in this document, but for now it does a good job of fulfilling its purpose:
>Define the submission and follow-up process of reporting security issues to Ory.
tagging you for review, since you wrote it zepatrik
> feat: bug bounty doc

- docs/docs/ecosystem/deployment.md
Clarifies which databases are supported as this was causing some confusion. 
I was not sure if SQLite should be in the list as "first-class citizen"; 
should SQLite generally not be used in production, or just not for Ory Keto?
> docs: clarify which databases are supported

- docs/sidebar.json
Looks like this is breaking docs build for Kratos:
```
Error: Server responded to https://raw.githubusercontent.com/ory/docs/master/docs/docs/concepts/email.md with status code 404:
404: Not Found
```
Not 100% sure I get this right though.
> fix: docs build in Kratos

- docs/docs/concepts/password-policy.mdx
- docs/sidebar.json
It is pretty similar to https://www.ory.sh/kratos/docs/next/concepts/security/#password-policy
But it describes the currently implemented password policy in Ory Cloud.
> docs: ory cloud password policy

- docs/docs/concepts/project-membership.mdx
- docs/sidebar.json
Project Invites Cloud documentation.
The documentation addresses:
- membership
- invite flows
- invite states
- project seats
- member roles
> feat: project invite cloud docs

- .github/workflows/markdownlint.yml
- docs/markdownlint.yml
adds the markdownlint configuration and github action.
this already provides a good baseline for uniform markdown formatting. 
with vale we can then add styles for the wording.
i think this is the feature you also requested:
https://github.com/markdownlint/markdownlint/issues/25
> feat: markdownlint

- docs/oathkeeper/guides/traefik-proxy-integration.md
- docs/oathkeeper/index.md
- docs/oathkeeper/pipeline/error.md
- src/sidebar.js
This PR contains the documentation for the updates done in https://github.com/ory/oathkeeper/pull/904.
> docs: traefik support

- docs/kratos/self-service.mdx
- docs/kratos/self-service/flows/account-recovery.mdx
- docs/kratos/self-service/flows/user-login.mdx
- docs/kratos/self-service/flows/user-registration.mdx
- docs/kratos/self-service/flows/user-settings.mdx
- docs/kratos/self-service/flows/verify-email-account-activation.mdx
[#1969
](https://github.com/ory/kratos/issues/1969)
[contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
vulnerability. If this pull request addresses a security. vulnerability, I
the changes.
works.
> fix: use HTTP 303 instead of 302 for selfservice redirects

- docs/guides/ory-cli-install-use.mdx
This is a minor addition to the CLI installation documentation with NPM.
> docs(CLI): extend the NPM installation instructions

- docs/ecosystem/styleguide/styleguide.md
- docs/ecosystem/styleguide/templates.md
- docs/ecosystem/styleguide/testing.md
- src/sidebar.js
since the last one got overwritten probably:
- adds a docs style guide 
+ a section explaining the testing (we can probably add a play playwright section too)
+ frontmatter template (we can add more over time)
---
- docs: add style guide
- ch ore: format
- chore: format
- chore: fix links
- fix: sidebar
> docs: style guide

- .github/workflows/vale.yml
Changees the Vale Github action to fail silently and only output annotations for lines that got changed.
> fix: vale github action

- docs/ecosystem/versioning.md
Since people keep missing the notice, I moved it to the top and made it __bold__. 
It should be clear now that this document is not about production readiness but more about the development process / handling backwards breaking changes.
- docs: clarify versioning/maturity
> docs: clarify versioning

- docs/hydra/concepts/oauth2.mdx
update outdated document title
> chore: fix outdated doc title

- docs/hydra/configure-deploy.mdx
Before one version was pulled but another one was ran.
See `$ docker pull oryd/hydra-login-consent-node:v1.10.6` above the line I changed.
> docs: Sync Docker image versions

- docs/kratos/concepts/browser-redirect-flow-completion.mdx
You would use the same config for JSON or browser redirect, just use a different Accept header, right? 
Then we could restructure this doc a bit. 
Anyway let me know this is enough.
> docs: clarify redirects json

- .github/workflows/vale.yml
- docs/.vale.ini
- fix: alertLevel Vale
- fix: remove debug mode vale
This sets the alert level of Vale to "error" and removes the "debug" mode, so the CI fails on errors. 
warnings and suggestions should be fixed, but dont make the CI fail (sometimes you need for example "passive voice") 
Also removes the microsoft styleguide, since its overly opinionated. 
We should make our own ruleset for Vale
> fix: vale linter

- docs/hydra/advanced.md
- docs/hydra/guides/updating-claims-at-refresh.mdx
- src/sidebar.js
Moved the existing content to a separate doc and made the description clearer.
> docs: updating claims on token refresh

- src/sidebar.js
> chore: sidebar duplicate

- docs/concepts/identity.mdx
The sentence misses the Grammer!
the changes.
> chore: sentence fix

- docs/hydra/sdk/go.mdx
@gen1us2k the build was failing on master because the imports were not in an mdx code block. Please always add react code to mdx code blocks to prevent issues like these and some others too :)
> fix: build issues with mdx block

- docs/_common/features/webauthn/configuration.mdx
Property `methods` should be a direct child to property `selfservice` in the documented config.yml example for webauthn, instead of a child to `flows`.
[https://github.com/ory/kratos/issues/2414](https://github.com/ory/kratos/issues/2414)
- [ X] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [X ] I have read the [security policy](../security/policy).
- [X ] I confirm that this pull request does not address a security
the changes.
works.
- [X ] I have added necessary documentation within the code base (if
appropriate).
> docs: fix webauthn configuration documentation

- docs/keto/guides/rbac.mdx
the changes.
works.
appropriate).
> fix: added rbac guide for keto

- docs/hydra/guides/openid-connect-dynamic-client-registration.mdx
The dynamic client registration endpoint was specified at /openid/register, but Ory Hydra exposes it at /oauth2/register.
Ory Hydra OpenAPI specification was fixed in this PR: https://github.com/ory/hydra/pull/3141
the changes.
works.
appropriate).
Will sign the CLA once clarified with my superior.
> fix: dynamic client registration path in hydra docs

- code-examples/protect-page-login/go/handler.go
- code-examples/protect-page-login/go/main.go
- code-examples/protect-page-login/go/middleware.go
If a beginner attempts to use the pattern from the code in the Go example middle-ware, they'll see some unexpected issues.
`App` is shared across requests so if more then one request is being processed there is a race condition.
This PR will remove that issue by using just the request's context to pass values around.
> feat: use context in Go example middleware

- docs/guides/session-management/overview.mdx
Just fixing a tiny typo! ✍️ 🙏 
> docs: fix typo in session management overview page

- src/pages/_assets/examples-content.tsx
the flutter link to https://www.ory.sh/docs/getting-started/integrate-auth/react-native is broken 
- took the chance to also update the other links and add the new react native guide. 
lets merge it soona as the link is broken @tomekpapiernik 🙏
> chore: fix examples links +add react native

- docs/hydra/guides/updating-claims-at-refresh.mdx
This change adds docs for https://github.com/ory/hydra/issues/3203 and https://github.com/ory/hydra/pull/3204
This is a companion change for https://github.com/ory/hydra/pull/3204, so it will be ready for review when the other change is ready.
> feat: add docs for session and requester fields in Hydra refresh webhook

- docs/oathkeeper/grpc-middleware.md
- src/sidebar.js
Documentation for the Oathkeeper gRPC middleware implemented in https://github.com/ory/oathkeeper/pull/1004.
> docs: add doc for grpc middleware

- docs/hydra/security-architecture.md
I think that is will link to RFC 6819 home instead section 5.1.5.3
> fix: link to RFC 6819 home instead section 5.1.5.3

- src/sidebar.js
I got some feedback that the NextJs example would be more fitting in the SSA category than SPA. 
(also see [auth0 examples](https://auth0.com/docs/quickstarts))
Another thing was that Flutter should also be under native/mobile, but I was not sure since the example seems to be for Flutter Web, which is not used for mobile/native?
Maybe we should rename it to Flutter Web in the sidebar if its not usable for mobile/native dev
> docs: move nextjs example

- docs/hydra/advanced.md
- docs/hydra/guides/gitlab.mdx
- docs/kratos/_common/oidc_session_hook.mdx
- docs/kratos/manage-identities/05_identity-schema.mdx
- docs/kratos/self-service/flows/user-logout.mdx
- docs/kratos/social-signin/01_overview.mdx
- docs/kratos/social-signin/10_google.mdx
- docs/kratos/social-signin/15_facebook.mdx
- docs/kratos/social-signin/20_microsoft.mdx
- docs/kratos/social-signin/25_github.mdx
- docs/kratos/social-signin/30_apple.mdx
- docs/kratos/social-signin/35_gitlab.mdx
- docs/kratos/social-signin/40_auth0.mdx
- docs/kratos/social-signin/45_slack.mdx
- docs/kratos/social-signin/50_spotify.mdx
- docs/kratos/social-signin/55_discord.mdx
- docs/kratos/social-signin/60_twitch.mdx
- docs/kratos/social-signin/65_netid.mdx
- docs/kratos/social-signin/70_yandex.mdx
- docs/kratos/social-signin/75_vk.mdx
- docs/kratos/social-signin/80_dingtalk.mdx
"log in" and "log out" are verbs, and "login" and "logout" are nouns in English. Previously the docs used "login" and "logout" as verbs. I also fixed a couple minor issues that I noticed while making these corrections.
> docs: fix "log in" and "log out" as verbs

- docs/kratos/emails-sms/05_custom-email-templates.mdx
According to the documentation the templates should be defined in `courier` and not `smtp`.  After testing this locally this also seems the case.
With `smtp`:
config:
```
smtp:
templates:
recovery:
valid:
email:
body: 
html: file:///etc/kratos/templates/recovery/valid/email.body.gotmpl
plaintext: file:///etc/kratos/templates/recovery/valid/email.body.plaintext.gotmpl
subject: file:///etc/kratos/templates/recovery/valid/email.subject.gotmpl
``` 
With the correct `courier`:
config:
```
courier:
...
templates:
recovery:
valid:
email:
body: 
html: file:///etc/kratos/templates/recovery/valid/email.body.gotmpl
plaintext: file:///etc/kratos/templates/recovery/valid/email.body.plaintext.gotmpl
subject: file:///etc/kratos/templates/recovery/valid/email.subject.gotmpl
``` 
If this pull request …
> docs: update incorrect information about courier templates

- docs/kratos/self-service/flows/user-login.mdx
- docs/kratos/self-service/flows/user-registration.mdx
- docs/kratos/self-service/flows/user-settings.mdx
- package-lock.json
Adds an example to the oidc code boxes, since the method is enabled (for quite some time now ;))
also fixes package-lock so `npm ci` works again
> fix: oidc example code cloud

- docs/hydra/production.md
- docs/keto/guides/production.md
Updates the current "prod" guide for Keto to a "prepare for production" guide as we have in Hydra, with a similar structure - this should stop the bleeding until we create a proper "selfhosted" section for Keto. 
Also a few stylistic changes in the Hydra guide.
> fix: update keto prod guide

- docs/ecosystem/security.md
This pull request removes a link to the HackerOne bounty program that was 404'ing and replaces it with a link to the email address where someone could request access to the bounty program. 
> chore: add email address for bounty program access

- docs/kratos/session-management/01_overview.mdx
Documentation was missing closing quotation marks. So, the examples didn't work when trying to copy-paste
> docs: add missing closing single quotation marks

- docs/kratos/social-signin/10_google.mdx
This PR updates the needed scopes for using Google as Social IDP.
As suggested by the old version of the docs, the scopes are invalid:
Changing them to profile works:
> docs: updated scopes for google sidp

- docs/keto/guides/expand-api-display-who-has-access.mdx
- docs/keto/guides/list-api-display-objects.mdx
- docs/keto/guides/simple-access-check-guide.mdx
This PR quickly explains the usage of the new --insecure flags in the Keto CLI.
Blocked by https://github.com/ory/keto/pull/991
> docs: explain insecure Keto CLI flag

- docs/kratos/sdk/05_go.mdx
I believe the admin port should be `4434` not `4443`. Or did I miss something, where the port for that specific part is set to that?
> chore: fix kratos admin api port

- docs/ecosystem/community.md
adds a new community project. 
Also remove the kratos/hydra integration tests/branches as this is now out-of-the-box
I will give this whole document some more love soon, right now just documenting the loopback4 project.
> docs: new community resources

- README.md
- src/pages/_assets/examples-content.tsx
Adds a new community example of how to use Ory Hydra with Java and Spring.
Also fixes some small errors in `README.md` around committing examples:
- path included the repository name when I believe the intent is to use the path relative to this this repository
- linter does not allow single quotes (`'`) so the example has been updated with the expected double quote (`"`) usage
- linter requires a trailing comma (`,`) so the example has been updated with the expected trailing comma
N/A.
N/A.
> docs: update community examples with Hydra Java example

- docs/kratos/debug/troubleshooting.md
Removes an outdated FAQ item that points to a missing section.
Also this should not be there keeping in line with "document what is possible, not what is not possible"
> fix: outdated faq

- code-examples/sdk/go/selfservice/whoami.go
- code-examples/sdk/go/session/refresh-session.go
- code-examples/sdk/typescript/src/selfservice/session/whoami-native.ts
- code-examples/sdk/typescript/src/selfservice/session/whoami-react.tsx
- code-examples/sdk/typescript/src/session/delete-sessions-native.ts
- code-examples/sdk/typescript/src/session/disable-session-native.ts
- code-examples/sdk/typescript/src/session/get-identity-sessions-native.ts
- code-examples/sdk/typescript/src/session/get-session-native.ts
- code-examples/sdk/typescript/src/session/get-sessions-native.ts
- code-examples/sdk/typescript/src/session/init-client-native.ts
- code-examples/sdk/typescript/src/session/refresh-session-native.ts
- docs/kratos/session-management/01_overview.mdx
- docs/kratos/session-management/10_session-lifespan.mdx
- docs/kratos/session-management/20_refresh-extend-session.mdx
- Refreshing overview, lifespan and refresh/extend documentation
- Drop `Session` blob in the doc and link to API reference
> docs: refresh session lifespan, extend samples

- docs/keto/guides/userset-rewrites.mdx
Fixes a typo in the tips section toward the bottom of [this page](https://www.ory.sh/docs/keto/guides/userset-rewrites), where an npm install command points to `@ory/keto-namespaces-types` instead of `@ory/keto-namespace-types`
> fix: corrected typo in OPL npm install command

- README.md
- src/theme/ketoRelationsPermissionsPrism.js
- src/theme/prism-include-languages.js
- src/utils/prismLight.mjs
This adds a new language to represent the new relationship string format, as well as re-enables syntax highlighting for the current relation tuples.
> feat: enable syntax highlighting for relationtuples and relationships

- docs/kratos/social-signin/05_generic.mdx
- docs/kratos/social-signin/10_google.mdx
- docs/kratos/social-signin/15_facebook.mdx
- docs/kratos/social-signin/20_microsoft.mdx
- docs/kratos/social-signin/25_github.mdx
- docs/kratos/social-signin/30_apple.mdx
- docs/kratos/social-signin/35_gitlab.mdx
- docs/kratos/social-signin/40_auth0.mdx
- docs/kratos/social-signin/45_slack.mdx
- docs/kratos/social-signin/50_spotify.mdx
- docs/kratos/social-signin/55_discord.mdx
- docs/kratos/social-signin/60_twitch.mdx
- docs/kratos/social-signin/65_netid.mdx
- docs/kratos/social-signin/70_yandex.mdx
- docs/kratos/social-signin/75_vk.mdx
- docs/kratos/social-signin/80_dingtalk.mdx
- docs/kratos/social-signin/81_lark.mdx
Ory Console has recently added support for several new social sign-in providers, which are not yet documented. This PR adds a new **Ory Console** tab to the docs for each of these providers, giving the instructions to enable the provider in the Ory Console
Issue is https://github.com/ory-corp/cloud/issues/3726
> docs: add missing Ory Console tabs for social sign-in providers

- docs/kratos/concepts/security.mdx
- docs/troubleshooting/10_crsf.mdx
Adds explanation to the security / threat model document on how Ory Identities handles CSRF attacks.
> docs: explain csrf defenses

- docs/_common/secure.mdx
fixes the "secure" admonition from this PR https://github.com/ory/docs/pull/1252/
Sorry should not have merged before checking that it actually renders correctly. 
Should be fine now. 
PTAL @tomekpapiernik
> fix: secure admonition

- docs/guides/integrate-with-ory-cloud-through-webhooks.mdx
The `flows.registration.after.hooks` section is used only if the `flows.registration.after.{password,oidc}` sections are empty.
This was confusing to users, because by default we have the `session` hook in this section, which would then case the webhooks in the "global" section to not be sent.
> fix: actions configuration

- docs/keto/sdk/05_go.mdx
Updating a link in the documentation that was pointing to localhost
> docs: replace link to localhost host with link to documentation site

- README.md
adds a link to a cheatssheet with detailed tips for mermaid.js diagrams.
> docs: mermaid tips in README

- docs/concepts/cache.mdx
- docs/identities/sign-in/check-session.mdx
Reverts ory/docs#1283
We identified the root cause of the behavior, and it is no longer needed to include this cookie.
DO NOT MERGE
> Revert "docs: clarify the need for __cflb cookie" - don't merge yet

- docs/hydra/self-hosted/production.md
- docs/keto/guides/production.md
- docs/kratos/guides/production.md
as discussed here, this removes the scary admonition with something more helpful, and streamlines it across the projects: https://github.com/ory/docs/pull/1312
> docs: self-host production intro

- docs/kratos/mfa/15_totp.mdx
This issue was raised because a user was confused by the fact that TOTP is not automatically enabled on a user account, after it has been enabled on the project. Users need to access Account Settings and enable TOTP themselves. As well as clarifying this point, I added more details about the procedures for end users in the Ory Account Experience.
> docs: added missing steps in MFA (TOTP) docs

- docs/self-hosted/operations/15_observability.md
Forgot to add the Oathkeeper port in my previous PR. 
Also words the sentence less confusing, they all have the same endpoint but different ports in the default configuration.
> fix: add oathkeeper obs port

- docusaurus.config.js
Implements the universal convention whereby the company logo in the top right of the page brings you to the main corporate web site. This also makes the "Website" link on the navbar redundant.
> docs: make Ory logo link to website, and remove obsolete Website link

- docs/getting-started/custom-ui.mdx
- docs/kratos/bring-your-own-ui/01_overview.mdx
- src/pages/_assets/examples-content.tsx
- src/sidebar.js
- creates separate page and sidebar item for custom ui examples/quickstarts
- adds a mention of the custom ui examples on next steps of custom UI overview.
tangentially related minor fixes:
- removes outdated supabase example from overview
- minor style improvements
We can probably link to the custom ui examples in other places as well, but this felt like the most natural start - I did not want to go through all docs and see where it could fit.
> fix: split up custom ui examples

- docs/hydra/self-hosted/configure-deploy.mdx
- docs/hydra/self-hosted/deploy-hydra-example.mdx
- docs/kratos/guides/deploy-kratos-example.mdx
changes the code snippets to show latest version. 
(to prevent [gpt bot](https://app.kapa.ai/conversations/94164c1a-d0f5-4139-a0a6-ba0e10d4853e?projectId=clheldcpm00033b6pb98cagzl) answers with outdated versions)
> fix: self-hosted deploy guides latestversion

- docs/oathkeeper/configure-deploy.mdx
Simple fix for missing EOF, causing shell block when copy.
> fix: missing eof

- docs/kratos/manage-identities/25_import-user-accounts-identities.mdx
Document the addition of `crypt(3)` functions, how they are used and the supported format.
* https://github.com/ory/kratos/pull/3303
* https://github.com/ory/kratos/issues/3291
> docs: crypt import

- docs/hydra/cli/hydra-create-client.md
Update the hydra create client docs to add the flag skip-consent to allow skip consent screen for this client.
> docs: add skip consent flag

- docs/keto/concepts/15_subjects.mdx
Fixed typo in documentation for subjects (Object vs Subject)
> chore: fix typo

- docusaurus.config.js
> fix: link to github discussions

- docs/oauth2-oidc/claims-scope.mdx
- src/sidebar.js
Closes https://github.com/ory-corp/cloud/issues/4857
> docs: explain default claims mapping

- docs/guides/cors.mdx
- docs/guides/custom-domains.mdx
- src/sidebar.js
This is very minimal right now, but I was not sure what else to add.
> feat: add Ory Network CORS documentation

- docs/kratos/social-signin/40_auth0.mdx
Docs for https://github.com/ory-corp/cloud/pull/4936
Inspired by our old docs, which had the information: https://github.com/ory/kratos/blob/b1f1da2c0b4fbf6e6b4259c58b39a3e88e990142/docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx#L471-L476
> fix: tenant URL for Auth0

- code-examples/sdk/typescript/src/oauth2/consent-verbose.ts
the consent-verbose example is a copy of login-verbose. This patch changes it a correct example code.
https://www.ory.sh/docs/oauth2-oidc/custom-login-consent/flow#consent-endpoint-code-example
I am not 100% sure if this is the correct code example, but that was what we had before from https://github.com/ory/hydra-login-consent-node/blob/master/src/routes/consent.ts
> fix: consent-verbose code example

- docs/hydra/login-consent-flow.md
- docs/kratos/self-hosted/03_mail-courier-http.mdx
The documentation is inconsistent with the format Kratos configuration expects, this PR brings them inline. 
1) `headers` is plural in the schema
```
"headers": {
"type": "object",
"description": "The HTTP headers that must be applied to request",
"additionalProperties": {
"type": "string"
}
},
```
2) `email.strategy` was later replaced with `delivery_strategy`
https://github.com/ory/kratos/issues/3392
> docs: makes Courier http doc consistent with kratos configuration

- docs/kratos/social-signin/09_ory.mdx
- src/sidebar.js
documentation how to add Ory OAuth2/Hydra as SSO provider to Ory Identities.
its pretty much the generic provider but added some commands how to create the OAuth2 client.
PR for console coming soon
> fix: social signin SSO Ory

- docs/kratos/emails-sms/05_custom-email-templates.mdx
Adjusts the email template variable section to make it easier to understand and adds a note on why we don't include a link to the recovery form.
> chore: adjust email template variable section

- docusaurus.config.js
Widget now only executes the script file once the HTML document has been fully parsed.
Also added a privacy disclaimer.
> fix: add gpt widget again

- vercel.json
@LBBO this new cache logic lead to quite serious problems on the documentation. The reason is that it simply is a catch-all cache which sets an insanely high lifetime. This leads to (in hindsight) very obvious problems:
- All pages, all HTML, all images, all assets - everything is cached for basically forever
- If all HTML is cached forever, it may very well refer to old assets which no longer exist both on th server and the client. This breaks the site (see for example #1489)
- Because we use cloudflare with edge caching, and it is also explicitly enabled by the `public` directive. This not only stores outdated assets (such as HTML pages) on the client - it stores them in Cloudflare. This significantly makes the problem of broken pages worse due to a shared state.
Caching is not an easy …
> revert: cache change

- .github/workflows/playwright.yml
- code-examples/protect-page-login/flutter_web_redirect/env
- code-examples/protect-page-login/flutter_web_redirect/lib/main.dart
- code-examples/protect-page-login/flutter_web_redirect/lib/services/auth.dart
- code-examples/protect-page-login/flutter_web_redirect/pubspec.lock
- code-examples/protect-page-login/flutter_web_redirect/pubspec.yaml
- docs/getting-started/integrate-auth/20_flutter-web-redirect.mdx
This PR installs new versions of dependencies, fixes Ory base URL used for Ory Proxy and updates the guide. 
> docs: update Flutter Web Example 

- docs/guides/integrate-with-ory-cloud-through-webhooks.mdx
> docs: update webhooks ips

- docs/account-experience/index.mdx
- docs/kratos/bring-your-own-ui/01_overview.mdx
- src/sidebar.js
All sections on the overview page could go into their own page with more content, but having the basics all on one page for now is already better than nothing.
> feat: initial account experience docs

- code-examples/sdk/typescript/src/selfservice/registration/apple-social-sign-in-native.ts
- docs/kratos/social-signin/30_apple.mdx
- docs/kratos/social-signin/96_native-apps.mdx
https://github.com/ory/kratos/pull/3476
> feat: add docs for native sign in using Apple SDK

- docs/troubleshooting/10_crsf.mdx
closes https://github.com/ory/network/discussions/338
> fix: public suffix debug

- docs/hydra/guides/updating-claims-at-refresh.mdx
Docs for https://github.com/ory/hydra/pull/3633
> feat: add OAuth2 token hook authentication

- docs/kratos/organizations/organizations.mdx
> feat: update b2b sso organization documentation

- docs/oauth2-oidc/resource-owner-password-grant.mdx
- src/sidebar.js
> feat: document rop grant

- docs/guides/rate-limits.mdx
- src/sidebar.js
> chore: document rate-limits

- docs/keto/guides/rbac.mdx
> docs: update RBAC guide

- src/theme/Mermaid.js
This pull request adds the dark mode theme for mermaid diagrams that match the selected theme.
#1213 
This fix only applies after a page refresh if the page has a diagram. This is due to the mermaid package refreshing it empty (and I don't know why).
We can open a new issue to fix this bug later, while still keeping diagrams more visible than today.
> fix: add dark mode for diagrams (#1213)

- docs/kratos/social-signin/95_account-linking.mdx
> feat: account linking docs

- docs/kratos/self-hosted/10_sending-sms.mdx
> chore: add request_url

- docs/oauth2-oidc/jwt-access-token.mdx
> feat: document mirror_top_level_claims

- docs/oathkeeper/pipeline/authz.md
✨(authorizers): for remote_json, introduce the ability to specify headers
https://github.com/ory/oathkeeper/issues/969
Corresponding changes in oathkeeper https://github.com/ory/oathkeeper/pull/1140
> docs: for remote_json authorizer, add headers

- docs/identities/sign-in/actions.mdx
- docs/kratos/self-service/flows/verify-email-account-activation.mdx
> feat: add docs for verification after login

- docusaurus.config.js
Renaming the kapa modal from "Copilot" to "Help?" after a user suggestion. 
I think its a bit more enticing to click on like this and would help more users find the bot.
> fix: rename modal to help

- docs/security-compliance/personal-data-location.md
fixes an erroneous comma in the paragraph describing data region selection for personal data
> fix: typo in personal-data-location.md

- docs/oauth2-oidc/refresh-token-grant.mdx
[This page](https://www.ory.sh/docs/hydra/guides/client-token-expiration#refresh-token) mentions that the default refresh token in Ory lasts for 30 days, and that's what we found out when we tried. So unless the two pages are talking about different refresh tokens, 1 hour is incorrect and this PR is to fix that.
> fix: correct default refresh token TTL

- docs/kratos/manage-identities/25_import-user-accounts-identities.mdx
> fix: clarify ssha hash examples

- docs/ecosystem/security.md
> chore: update security policy

- docs/oathkeeper/pipeline/authn.md
Cache configuration documentation is missing the `max_cost` option.
Link: https://www.ory.sh/docs/oathkeeper/pipeline/authn#oauth2_introspection-configuration
Related Oathkeeper PR: https://github.com/ory/oathkeeper/pull/1176
> chore: add oathkeeper authn oauth2 introspection max_cost configuration

- docs/hydra/reference/configuration-editor.mdx
- src/components/ConfigEditor/index.tsx
- src/css/theme.css
This fixes the configuration editor for
- Kratos
- Keto
The editors for hydra & oathkeeper are broken for other reasons:
- Hydra: the spec references a non-existant tracing schema
- Oathkeeper: didn't investigate, probably a similar issue
Partially adresses: https://github.com/ory/docs/issues/1640 
> fix: configuration editor rendering

- docs/kratos/emails-sms/05_custom-email-templates.mdx
- src/components/ConsoleLink/console-nav-data.ts
> feat: update email template docs

- docs/migrate-to-ory/index.mdx
- src/sidebar.js
> feat: general migration guide

- docs/kratos/manage-identities/25_import-user-accounts-identities.mdx
> feat: document partial batch insert

- docs/oathkeeper/api-access-rules.md
> chore(typo): Remove the extra 'is', and correct to Rules

- docs/identities/sign-in/actions.mdx
- docs/identities/sign-in/identifier-first-authentication.mdx
- docs/identities/sign-in/two-step-login.mdx
- src/sidebar.ts
> docs: identifier first authentication

- docs/api/index.mdx
- docs/guides/permissions/overview.mdx
- docs/hydra/sdk/05_go.mdx
- docs/hydra/sdk/10_js.mdx
- docs/keto/sdk/05_go.mdx
- docs/keto/sdk/10_python.mdx
- docs/kratos/sdk/05_go.mdx
- docs/reference/api.mdx
- docs/sdk.mdx
- src/sidebar.ts
> docs: sidebar adjustments

- docs/kratos/organizations/organizations.mdx
- docs/kratos/social-signin/oidc-pkce.mdx
- src/sidebar.js
- src/sidebar.ts
> feat: document PKCE during social sign-in

- docs/getting-started/_common/ory-cli.mdx
- docs/getting-started/integrate-auth/01_go.mdx
- docs/getting-started/integrate-auth/05_php.mdx
- docs/getting-started/integrate-auth/10_expressjs.mdx
- docs/getting-started/integrate-auth/15_nextjs.mdx
- docs/getting-started/integrate-auth/20_flutter-web-redirect.mdx
- docs/getting-started/integrate-auth/25_react.mdx
- docs/getting-started/integrate-auth/30_vue.mdx
- docs/getting-started/integrate-auth/40_dotnet.mdx
- docs/guides/cli/20_proxy-and-tunnel.mdx
> chore: improve Ory CLI usage in auth guide

- docs/actions/live-events.mdx
> docs: add initial description of all events

- docs/oauth2-oidc/refresh-token-grant.mdx
A prospect stumbled over this, expecting a refresh token from the code exchange but only getting an access token because they were missing the `grant_type=refresh_token` in their client configuration.
> fix: clarify requirements for obtaining a refresh token

- docs/oauth2-oidc/resource-owner-password-grant.mdx
> feat: more rop claims

- docs/hydra/guides/graceful-token-refresh.mdx
- src/sidebar.ts
> docs: graceful token refresh

- docs/guides/integrate-with-ory-cloud-through-webhooks.mdx
> chore: update interrupting webhooks examples payload

- docs/hydra/reference/configuration.mdx
- docs/keto/reference/configuration.mdx
- docs/kratos/reference/configuration.mdx
- docs/oathkeeper/reference/configuration.mdx
- package.json
- src/components/ConfigMarkdown/index.tsx
After this change, we use the complete rendered config from the latest release. The sub-schemas for tracing and logging are generated in the individual repos.
Ref https://github.com/ory/oathkeeper/pull/1202 needed for oathkeeper to work.
> fix: configuration reference

- docs/troubleshooting/45_passkeys-webauthn-security-error.mdx
We use this page in Ory Kratos to notify the user with a helpful error message about their passkey set up.
> docs: add webauthn / passkey troubleshoot

- docs/kratos/social-signin/20_microsoft.mdx
@vinckr changelog pls
> In the case of Microsoft, using sub as an identifier can lead to problems. Because the use of OIDC at Microsoft is based on an app registration, the content of sub changes with every new app registration. Sub is therefore not uniquely related to the user. It is therefore not possible to transfer users from one app registration to another without further problems.
https://learn.microsoft.com/en-us/entra/identity-platform/id-token-claims-reference#payload-claims
> With the use of oid it is possible to identify a user by a unique id.
> docs: support for oid microsoft parameter

- docs/identities/session-to-jwt-cors.mdx
> chore: clarify jwt tokenizer

- docs/guides/integrate-with-ory-cloud-through-webhooks.mdx
- docs/kratos/emails-sms/05_custom-email-templates.mdx
> fix: transient payload in email templates

- docs/oathkeeper/pipeline/mutator.md
Relates to https://github.com/ory/oathkeeper/pull/1177
> feat: add id_token mutator cache config

- code-examples/migrate-to-ory/0-get-auth0-user-data.sh
For auth0 export jobs against connections with a large number of users, there's an additional job state, `processing`, which does not seem to be accounted for. 
This fix treats the handling of `processing` like `pending`, waiting for the job to finish before moving on to the next step.
> fix: handle auth0 export job state of "processing"

- docusaurus.config.ts
- src/theme/KapaWidget.css
- src/theme/KapaWidget.tsx
- src/theme/Root.js
> feat: load kapa async on click

- docs/kratos/manage-identities/25_import-user-accounts-identities.mdx
> chore: clarify 403 response in PW migration hook

- docs/kratos/emails-sms/05_custom-email-templates.mdx
- docs/kratos/mfa/30_sms.mdx
> chore: add docs for code MFA

- docs/self-hosted/oel/oauth2/postgresql-ttl-migrations.mdx
- src/sidebar.ts
> docs: describe postgresql ttl jobs

- src/theme/Mermaid.js
> fix: mermaid diagram render

- code-examples/protect-page-login/php/app.php
- docs/getting-started/integrate-auth/05_php.mdx
> docs: update php quickstart

- src/theme/Mermaid.js
- src/theme/SelfServiceApiFlow.js
- src/theme/SelfServiceBrowserFlow.js
- src/theme/SelfServiceSpaFlow.js
> fix: mermaid bug where some images don't render

- docs/kratos/emails-sms/05_custom-email-templates.mdx
* PR to introduce the `ExpiresInMinutes` field https://github.com/ory/kratos/pull/4104
As the title states, this is a simple suggestion to add the template variable to the docs.
> chore: add `ExpiresInMinutes` as an email template variable

- docs/oathkeeper/pipeline/mutator.md
Use permalink to cater for changes to the code base.
> fix(docs): Set Permalink URL to AuthenticationSession struct

- docs/kratos/emails-sms/05_custom-email-templates.mdx
> chore: add missing ExpiresInMinutes variables

- docs/kratos/organizations/organizations.mdx
> docs: added documentation for data mapping of SAML attributes

- docs/kratos/manage-identities/50_scim.mdx
- src/sidebar.ts
> feat: add SCIM docs

- docs/kratos/manage-identities/25_import-user-accounts-identities.mdx
> docs: clarify import limits

- docs/kratos/social-signin/98_line.mdx
- src/sidebar.ts
Document how to set up a LINE social sign-in.
Relates to https://github.com/ory/kratos/pull/4240
> feat: document LINE social sign-in provider

- docs/ecosystem/projects.mdx
> chore: remove outdated project graph

- docs/getting-started/integrate-auth/40_dotnet.mdx
- src/css/theme.css
Small fix for the dotnet quick start code blocks looking off.
- Removed `display: block` for add and delete lines css.
- Changed code blocks type from 'cshtml' to 'csharp' as cshtml is not supported.
Reference: Issue #2230
> fix(docs): fix dotnet quickstart code blocks

- docs/identities/model/identity-schema-selection.mdx
- src/sidebar.ts
docs for Identity Schema Selection feature
> feat: added first draft for identity schema selection

- docs/hydra/guides/cors.mdx
Closes https://github.com/ory/hydra/issues/3795
> docs: clarify CORS

- docs/kratos/concepts/security.mdx
- src/components/ConsoleLink/console-nav-data.ts
- part of https://github.com/ory-corp/cloud/issues/8260
> docs: captcha allowed domains customization
