- guides/1-hydra/7-sdk/3-php.md
Signed-off-by: Philip Nicolcev <phil.nicolcev@tulip.com>
> Fix PHP SDK README url.

- guides/1-hydra/2-overview/1-oauth2.md
Fixed small typo in documentation
> Fixed 1-oauth2.md typo

- guides/hydra/4-install/README.md
> Uses /dev/urandom to generate system secret

- guides/oathkeeper/1-overview/5-proxy-judge.md
Signed-off-by: arekkas <aeneas@ory.am>
> oathkeeper: Add more info judge/proxy mode

- guides/oathkeeper/1-overview/1-rules.md
Docs for the new `cookies` credentials issuer.
> oathkeeper: new cookies credentials issuer

- guides/oathkeeper/1-overview/1-rules.md
Signed-off-by: arekkas <aeneas@ory.am>
> oathkeeper: add jwt authorizer

- guides/hydra/1-tutorial/README.md
> fix hydra web server url

- guides/hydra/6-how-to/3-advanced.md
Signed-off-by: arekkas <aeneas@ory.am>
> hydra: add system secret rotation info

- guides/oathkeeper/1-overview/1-rules.md
relates to https://github.com/ory/oathkeeper/pull/129
> Update keto warden docs

- guides/hydra/6-how-to/4-debug.md
related: https://github.com/ory/hydra/pull/1132
👀 @aeneasr
> tracing-docs: remove bad config value + grammar fix

- guides/oathkeeper/1-overview/1-rules.md
* removed unnecessary comma
* fixed field name for aud check
* fixed values for aud and iss checks
> fixed example for jwt authenticator

- docs/ecosystem/versioning.md
- docs/hydra/configure-deploy.md
- website/versioned_docs/version-oryOS.9/ecosystem/versioning.md
- website/versioned_docs/version-oryOS.9/hydra/configure-deploy.md
> hydra: Release new software version

- docs/oathkeeper/api-access-rules.md
A tiny typo fix for issue #81 .
> Fix oathkeeper jwt authenticator config, issue #81

- docs/hydra/production.md
Accordring to REST API doc https://www.ory.sh/docs/hydra/sdk/api#retrieve-a-json-web-key-set
> Replace /jwks endpoint with /keys

- docs/hydra/production.md
Describe how to specify different interfaces or UNIX sockets to listen on.
Signed-off-by: Janis Meybohm <meybohm@traum-ferienwohnungen.de>
This is documentation for https://github.com/ory/hydra/pull/1230
> Add documentation for PUBLIC_HOST/ADMIN_HOST

- docs/ecosystem/community.md
> Add community section

- docs/keto/engines/acp-ory.md
- website/versioned_docs/version-oryOS.10/keto/engines/acp-ory.md
- website/versioned_docs/version-oryOS.9/keto/next/engines/acp-ory.md
I found this bug while reading through the documentation. Thought I can fix it quickly.
> Fixed documentation error, updated correct response from the API

- docs/keto/engines/acp-ory.md
- docs/keto/sdk/api.md
Documentation for https://github.com/ory/keto/pull/79
> Update documentation for glob support

- docs/keto/engines/acp-ory.md
Ref https://github.com/ory/keto/issues/82#issuecomment-479322618
> Fix options for StringMatchCondition

- docs/hydra/oauth2.md
> hydra: Update docs on query parameters and userinfo

- docs/ecosystem/usage.md
- website/sidebars-next.json
- website/sidebars.json
Signed-off-by: Kevin Minehart <kmineh0151@gmail.com>
> Add API Usage docs under ecosystem

- README.md
This should be helpful in warning future editors against the pitfall I just encountered. :baby:
> Update README.md: Add caveats for static resources

- docs/hydra/advanced.md
- docs/hydra/configure-deploy.md
- docs/hydra/faq.md
> hydra: upgrade migrate commands

- docs/hydra/install.md
- docs/keto/install.md
- docs/oathkeeper/install.md
- website/versioned_docs/version-oryOS.10/hydra/configure-deploy.md
- website/versioned_docs/version-oryOS.11/hydra/install.md
- website/versioned_docs/version-oryOS.11/keto/install.md
- website/versioned_docs/version-oryOS.11/oathkeeper/install.md
> Update install instructions for linux

- docs/ecosystem/versioning.md
- docs/hydra/configure-deploy.md
- docs/hydra/sdk/api.md
- website/versioned_docs/version-oryOS.11/ecosystem/versioning.md
- website/versioned_docs/version-oryOS.11/hydra/configuration.md
- website/versioned_docs/version-oryOS.11/hydra/configure-deploy.md
- website/versioned_docs/version-oryOS.11/hydra/sdk/api.md
- website/versioned_docs/version-oryOS.11/performance/hydra.md
> hydra: Release rc.11

- docs/ecosystem/database.md
add cockroachdb support info.
Related MR's:
`ory/x`:
https://github.com/ory/x/pull/40
`ory/hydra`:
https://github.com/ory/x/pull/40
Related issue:
https://github.com/ory/hydra/issues/990
Signed-off-by: David López <not4rent@gmail.com>
> all: add support for cockroachdb

- docs/hydra/configure-deploy.md
use /ready instead of /status for version rc11
> change health check url

- docs/oathkeeper/api-access-rules.md
- website/package-lock.json
- website/package.json
> Disable svg minification and fix broken link

- docs/ecosystem/cloud-native.md
This page could also be replaced with a link to https://12factor.net.
> Improve wording

- docs/oathkeeper/index.md
Mostly replaces passive voice (which is a no-no in English) with active voice. I also added mention of attribute-based access control as well as usage of some of its terminology (policy enforcement point, policy decision point). I found this model to be one of the more intuitive ones. Feel free to disagree on this or anything else, then I'll take these parts out.
> Simple grammar improvements for Oathkeeper intro

- .widdershins/config.json
- apis/hydra.json
- apis/keto-next.json
- apis/keto.json
- apis/oathkeeper.json
- markdown-link-check.json
- website/package.json
- website/sidebars-next.json
- website/sidebars.json
- website/versioned_sidebars/version-oryOS.10-sidebars.json
- website/versioned_sidebars/version-oryOS.11-sidebars.json
- website/versioned_sidebars/version-oryOS.9-sidebars.json
- website/versions.json
Prettier also allows formatting of JSON files.
> Prettier JSON files

- README.md
I think this reads slightly better.
> Document how to format

- docs/oathkeeper/api-access-rules.md
Ref: https://github.com/ory/oathkeeper/pull/213
> Document rules in YAML format

- docs/keto/engines/acl.md
- docs/keto/engines/acp-aws.md
- docs/keto/engines/rbac.md
- docs/keto/sdk/api.md
- docs/performance/hydra.md
- docs/performance/index.md
Going through the various changes on my computer made in the recent weeks on various flights/train rides.
> Stylistic and grammar improvements for Keto docs

- README.md
Hopefully, this makes other documentation contributions from the community easier.
> Local development instructions

- docs/oathkeeper/pipeline/mutator.md
Documentation update related to changes introduced in:
[oathkeeper/#240](https://github.com/ory/oathkeeper/pull/240)
> oathkeeper: Add information about Hydrator mutator

- docs/hydra/5min-tutorial.md
I write a quickstart for prometheus and create a [pull request](https://github.com/ory/hydra/pull/1562), 
and I think it's appropriate to add doc in this repo.
> Add doc for quickstart for prometheus.

- docs/oathkeeper/configure-deploy.md
If config not changed to my edit you will get this error:
time="2019-09-25T09:08:51Z" level=fatal msg="The configuration is invalid and could not be loaded." error="must validate at least one schema (anyOf)" validation_error[0]="mutators.header: Must validate at least one schema (anyOf)" validation_error[1]="mutators.header.config: config is required"
> Updated config.yaml example

- docs/oathkeeper/pipeline/authn.md
Use a list of string for trusted_issuers
> Fix example with jwt authenticator

- docs/hydra/configuration.md
> Fix typo in configuration file example

- docs/oathkeeper/configure-deploy.md
> oathkeeper: Clarify configuration section

- docs/hydra/debugging.md
> hydra: Add section to help with refresh token missing

- docs/hydra/debugging.md
> hydra: Add debug info for missing id_token

- docs/hydra/5min-tutorial.md
`hydra clients create` doesnt display the token anymore, so i removed the section dealing with the token
> removed the token introspection command

- website/versioned_docs/version-oryOS.11/hydra/oauth2.md
Forget to close ")".
so I fixed it.
> ')' Forget to close

- docs/keto/engines/acp-ory.md
Closes https://github.com/ory/keto/issues/141
> keto: Clarify glob matchin pattern

- docs/oathkeeper/pipeline/authn.md
Related to ory/oathkeeper#301 and ory/oathkeeper#302
> doc cookie and additional headers for introspection

- docs/oathkeeper/pipeline/authn.md
> document `preserve_path` for oathkeeper cookie_session authn

- docs/hydra/configuration.md
Making the example port match the default.
> Update Admin Port

- docs/ecosystem/overview.md
> Replaced _TBA_ identity management by ORY Kratos

- docs/hydra/implement-consent.md
Just add back quotes at hydra docs
> hydra: Add back quotes for counterpart

- .gitignore
- docs/hydra/sdk/api.md
- docs/keto/sdk/api.md
- docs/kratos/sdk/api.md
- docs/oathkeeper/api-access-rules.md
- docs/oathkeeper/configuration.md
- website/package-lock.json
This commit complements pull request https://github.com/ory/oathkeeper/pull/334.
Signed-off-by: Aynur Zulkarnaev <ayzulkarnaev@gmail.com>
> oathkeeper: document matching strategy

- docs/kratos/self-service/strategies/username-email-password.md
> feat: document password validation

- docs/hydra/advanced.md
- docs/hydra/configuration.md
Relates to https://github.com/ory/hydra/pull/1718
> docs: Add documentation around same site cookies in Hydra

- docs/ecosystem/roadmap.md
Basic layout for quick overview ORY roadmap.
> Added basic layout for roadmap

- docs/hydra/5min-tutorial.md
> fix: prometheus' targets link

- docs/oathkeeper/api-access-rules.md
- docs/oathkeeper/pipeline/authz.md
- docs/oathkeeper/pipeline/mutator.md
reference to https://github.com/ory/oathkeeper/pull/358
@aeneasr can you check if it misses something?
Thanks
> docs: add global auth session

- docs/oathkeeper/pipeline/authz.md
Check the links for instance to go template substitution.
> fix: reworked the file. the examples were not updated. 

- .widdershins/templates/responses.def
> fix: remove h3 from widdershins template

- scripts/config.js
Copied the changes from https://github.com/ory/hydra/pull/2161 to /docs
> docs: bcrypt reference config

- docs/README.md
- docs/contrib/config.js
- docs/contrib/sidebar.js
- docs/docusaurus.config.js
- docs/package-lock.json
- docs/package.json
- docs/scripts/config.js
- docs/scripts/docker-tag.js
- docs/scripts/fix-api.js
- docs/scripts/rerelease.js
- docs/src/pages/versions.js
- docs/src/theme/CodeFromRemote.js
- docs/src/theme/CodeFromRemote.module.css
- docs/src/theme/Footer/index.js
- docs/src/theme/Mermaid.js
- docs/src/theme/mermaid.module.css
Updated docusaurus template to current https://github.com/ory/docusaurus-template.
> chore: update docusaurus template

- docs/docs/ecosystem/contributing.md
Just some small corrections in the beginning before I put it into the sidebar.
> docs: fix up contributing

- docs/sidebar.json
> fix: broken sidebar config

- README.md
Some documenation how to add links to the docs and how to test locally.
More to follow...
> docs: add docs documenation

- README.md
Short guide how to add code from github directly 
& 
Header for documentation
> docs: guides/info on documenation

- docs/docs/ecosystem/projects.md
closes https://github.com/ory/docs/issues/373
> docs: fix typo

- docs/docs/ecosystem/community.md
- docs/docs/ecosystem/projects.md
Added some more recent community repositories and blog posts 
as well as the new github discussions as replacement for the forum.
> docs: community

- docs/docs/ecosystem/versioning.md
Added a notice to make clear that Kratos and Keto can be used in production, since that question comes up a lot. 
Most people read sandbox and experimental and think the project can not be used in production.
> docs: versioning notice

- docs/docs/ecosystem/community.md
Formatted everything more nicely, 
and added a few projects.
Also removed the privated  project.
> docs: community update

- docs/docs/ecosystem/community.md
Added the docker compose examples and articles from @radekg. 
Thanks a ton for the writeup and examples 🎉
> docs: community content

- docs/docs/ecosystem/community.md
Adding the Sveltekit example by @drejohnson to our community projects. 
Thanks a lot for your awesome work DeAndre 🙌 !
> docs: Sveltekit example

- README.md
Adds a small section explaining the formatting of Ory documentation.
> docs: add formatting notice

- README.md
as per https://github.com/ory/kratos/pull/1490#discussion_r666167642
> docs: update CodeFromRemote doc

- docs/docs/ecosystem/upgrading.md
Also added correct link for all newsletter links (http://eepurl.com/di390P)
> docs: add kratos to upgrade docs

- docs/docs/ecosystem/roadmap.md
An update to our OS roadmap 
closes https://github.com/ory-corp/product/issues/177
FYI @piotrmsc
> docs: os roadmap update

- docs/docs/concepts/identity.mdx
Should be merged with this: https://github.com/ory/kratos/pull/1639
> fix: model -> schema link

- docs/docs/early-access.mdx
> feat: public roadmap document

- docs/docs/ecosystem/community.md
Adding the `styx` project by @hrefhref 
As well as the `rescript` frontend by @allancalix
Both projects are exceptional work, looking very impressive from the first look!
Thanks so much for open sourcing your work and making the Ory community great 🎉
> docs: update community projects

- docs/docs/guides/proxy.mdx
As per https://github.com/ory-corp/cloud/issues/1352#issuecomment-897548305. 
How would the update work on Linux? Do you just run the install script again?
> fix: adding notice to update CLI

- docs/docs/early-access.mdx
> fix: typos in roadmap document

- docs/docs/concepts/terminology.mdx
- docs/sidebar.json
Documenting terms that are often used in Ory documentation and Ory Cloud specific terms.
> docs: terminology doc

- docs/docs/ecosystem/community.md
Thanks @unbuttun 🎉 
Will definitely play around with it soon.
> docs: add next.js example

- docs/docs/ecosystem/community.md
@blueacidfrog new community article about dockertest.
> docs: add dockertest article

- docs/docs/ecosystem/community.md
Categorizing the community projects, so people can find relevant code better. 
closes https://github.com/ory-corp/product/issues/209
> fix: categorize community projects

- docs/sidebar.json
closes https://github.com/ory/docs/issues/482
> fix: add deployment to sidebar

- docs/sidebar.json
also https://github.com/ory/docs/issues/482
> fix: add logging to sidebar

- docs/docs/concepts/personal-access-token.mdx
https://github.com/ory-corp/cloud/pull/1578
> docs: `ory_pat_` prefix

- docs/docs/get-started.mdx
- docs/docs/index.mdx
- docs/docs/start-building/create-project.mdx
fyi @aeneasr @blueacidfrog
ready to merge 😬
> docs: early access

- docs/docs/index.mdx
@blueacidfrog
closes https://github.com/ory-corp/product/issues/316
> fix: mention free plan cloud in welcome

- docs/docs/ecosystem/community.md
Thanks so much for contributing this handy tool @psauvage0 🎉 
Please reach out to me via email and we send you a gift.
> feat: add ketotodot project

- docs/docs/ecosystem/community.md
@atreya2011 adding your WIP project, great work thanks!
@sergiocarracedo Thanks for your article on dockertest, very cool!
Let us know if you would be interested in speaking at an Ory Event in the near future 😃
> docs: community projects

- docs/docs/cloud/developer.mdx
remove confusing/misleading wording
> fix: dev get started

- docs/docs/ecosystem/community.md
- fixes some outdated medium.com article links
> fix: broken links

- docs/docs/ecosystem/community.md
Gives each project a section and adds two missing articles.
Articles/code for several ory projects are at ory stack.
> fix: layout and add missing content

- docs/docs/ecosystem/deployment.md
closes https://github.com/ory/kratos/issues/1638
> docs: remove crdb beta

- docs/docs/guides/custom-domains.mdx
I could not really find the managed UI after setting up my CNAME, this will hopefully prevent others from searching :-).
> fix: clarify managed UI location

- docs/docs/ecosystem/community.md
Thanks a lot for this contribution @pngouin
I can't believe I missed this, very nice work!
Please [drop me an email](mailto:vincent@ory.sh) to claim your Ory Swag package as a small token of appreciation.
> docs: add community project

- docs/docs/start-building/server-side-web-app.mdx
- examples/typescript-express/package-lock.json
- examples/typescript-express/package.json
- examples/typescript-express/src/routes/protected.ts
changes the typescript expressjs example to use @ory/client instead of @ory/kratos-client. 
tested the example and it works just as before.
> fix: correct npm package in typescript example

- docs/hydra/reference/config.schema.json
- docs/hydra/reference/configuration-editor.mdx
- docs/keto/reference/configuration-editor.mdx
- docs/kratos/reference/config.schema.json
- docs/kratos/reference/configuration-editor.mdx
- docs/oathkeeper/reference/config.schema.json
- docs/oathkeeper/reference/configuration-editor.mdx
- package-lock.json
- package.json
- src/components/ConfigEditor/index.tsx
- src/css/theme.css
- src/sidebar.js
Thank you for the idea @vinckr @Benehiko 
I think this is not the best solution ever, but it's a bit better than just the text file. @vinckr looks like we need to add a lot of "title" and "description" values to the config items for the structure to look nicer :)
Maybe we can also add some type of YAML output of the current config somewhere...
> feat: configuration json schema live editor

- docs/hydra/cli/hydra-clients-create.md
- docs/hydra/cli/hydra-clients-delete.md
- docs/hydra/cli/hydra-clients-get.md
- docs/hydra/cli/hydra-clients-import.md
- docs/hydra/cli/hydra-clients-list.md
- docs/hydra/cli/hydra-clients-update.md
- docs/hydra/cli/hydra-clients.md
- docs/hydra/cli/hydra-janitor.md
- docs/hydra/cli/hydra-keys-create.md
- docs/hydra/cli/hydra-keys-delete.md
- docs/hydra/cli/hydra-keys-get.md
- docs/hydra/cli/hydra-keys-import.md
- docs/hydra/cli/hydra-keys.md
- docs/hydra/cli/hydra-migrate-sql.md
- docs/hydra/cli/hydra-migrate.md
- docs/hydra/cli/hydra-serve-admin.md
- docs/hydra/cli/hydra-serve-all.md
- docs/hydra/cli/hydra-serve-public.md
- docs/hydra/cli/hydra-serve.md
- docs/hydra/cli/hydra-token-client.md
- docs/hydra/cli/hydra-token-delete.md
- docs/hydra/cli/hydra-token-flush.md
- docs/hydra/cli/hydra-token-introspect.md
- docs/hydra/cli/hydra-token-revoke.md
- docs/hydra/cli/hydra-token-user.md
- docs/hydra/cli/hydra-token.md
- docs/hydra/cli/hydra-version.md
- docs/hydra/cli/hydra.md
- docs/hydra/guides/oauth2-grant-type-jwt-bearer.mdx
- src/sidebar.js
> docs: do not use emails as the primary identifier

- .github/workflows/vale.yml
- docs/.vale.ini
Adds the Vale Linter Action to improve consistency of style across the documentation.
It currently takes the write-good and Microsoft styles, both have reasonable suggestions. We could also add our own styles, or modify the existing.
https://github.com/vinckr/vale/
https://github.com/marketplace/actions/vale-linter
> feat: vale linter action

- docs/concepts/emails.mdx
- docs/concepts/identity.mdx
- docs/concepts/managed-ui.mdx
- src/components/Install/Linux.tsx
Started with linting the docs a bit according to the write-good and Microsoft styles. 
Let me know what you think, I would continue with the rest then.
- fix: stray dollersign
- fix: fix emails doc
- docs: fix identities doc
- docs: format identities doc
- docs: fix managed ui doc
- chore: format
> docs: style fixes

- docs/kratos/guides/sign-in-with-github-google-facebook-linkedin.mdx
There was some [confusion](https://github.com/ory/kratos/discussions/1186#discussioncomment-2228737) on how to add oidc config from environment variable. This example will be helpful.
> docs: provide example of setting oidc config from env var

- docs/get-started.mdx
- docs/sdk.mdx
deletes the empty documents, 
closes https://github.com/ory/docs/issues/610
Should be merged when https://github.com/ory/web/pull/591 has been merged
> chore: delete empty documents

- docs/oathkeeper/api-access-rules.md
the changes.
works.
appropriate).
> docs: better description of version tag for access-rules. closes #669

- src/plugins/ory-scripts-loader/ory-scripts-loader.js
Merge straight after https://github.com/ory/web/pull/595
> fix: pass container id into analytics initializer

- README.md
the changes.
works.
appropriate).
> docs: update readme code instructions

- README.md
the changes.
works.
appropriate).
> docs: add useful guides for working with MDX

- docs/hydra/index.md
the changes.
works.
appropriate).
> docs: fix typo in hydra introduction

- docs/keto/performance.mdx
the changes.
works.
appropriate).
> docs: fix a typo in keto performance docs

- docs/guides/protect-page-login/_common/teaser.mdx
- docs/guides/protect-page-login/go.mdx
- src/components/SdkEnvVar/index.tsx
- Updated Go guide to be more explicit and easy to follow
- Updated related reusables
> docs: update go getting started guide guide

- docs/kratos/guides/account-recovery-password-reset.mdx
Closes https://github.com/ory/kratos/issues/1077
> docs(kratos): invalidate sessions after recovery

- docs/kratos/self-service/hooks.mdx
See https://github.com/ory/kratos/pull/2266
> docs(kratos): non-blocking web hooks

- code-examples/protect-page-login/expressjs/routes/index.js
- docs/guides/protect-page-login/expressjs.mdx
Two small things I noticed why helping a user with this guide.
> fix: typo + example

- docs/kratos/quickstart.mdx
the changes.
works.
appropriate).
> docs: use latest version in quickstart

- docs/hydra/concepts/oauth2.mdx
- docs/hydra/debug.mdx
Hi. I detected errors for URLs in Hydra examples.
Corrected on the pages:
* https://www.ory.sh/docs/hydra/concepts/oauth2#oauth-20-refresh-tokens
* https://www.ory.sh/docs/hydra/debug#openid-connect-id-token-missing
the changes.
works.
appropriate).
> docs: fix query params for Hydra examples

- docs/_common/install.mdx
the changes.
works.
appropriate).
> fix: install link generation

- docs/hydra/configure-deploy.mdx
* better styles for examples
* Closes #651
the changes.
works.
appropriate).
> fix: more clear ports for the guide.

- src/components/Install/Windows.tsx
the changes.
works.
appropriate).
> chore: typo

- README.md
`#shell-examples` anchor doesn't work as the real anchor name is `#write-a-shell-example`.
I've changed the section title to **Shell Examples** so that it matches the table of contents.
the changes.
works.
appropriate).
> docs: fix "Shell Examples" anchor in README

- docs/kratos/guides/sign-in-with-github-google-facebook-linkedin.mdx
Closes https://github.com/ory/docs/pull/706
> feat: use id from https://graph.microsoft.com/v1.0/me as oidc subject

- docs/guides/social-signin/microsoft.mdx
- src/sidebar.js
the changes.
works.
appropriate).
Removed a completely empty document from the social sign-in section
> docs: cleanup social sign-in docs

- docs/guides/social-signin/microsoft.mdx
- src/sidebar.js
> revert: "docs: cleanup social sign-in docs"

- docs/_common/features/webauthn/configuration.mdx
the changes.
works.
appropriate).
> docs: fix incorrect statements

- docs/_common/jsonnetwarning.mdx
- docs/guides/customize-identity-schema.mdx
- docs/guides/social-signin/facebook.mdx
- docs/guides/social-signin/generic.mdx
- docs/guides/social-signin/github.mdx
- docs/guides/social-signin/google.mdx
- common markdown import for warning too not save secrets in ory cloud json/jsonnet
- add warning to social login guides
- add warning to customize identity schema guide
closes https://github.com/ory/docs/issues/705
The warning in the console should have the same wording, maybe we can link the console warning with this somehow @micleyman.
the changes.
works.
appropriate).
> docs: warning not to store secrets in jsonnet

- docs/guides/session-management/refresh-extend-session.mdx
the changes.
works.
appropriate).
Fixes a bug in the recent batch of merged docs where the `tip` frame-thing didn't end in the right spot and messed up the formatting of the majority of the page.
> chore: fix formatting bug

- docs/hydra/sdk/go.md
the changes.
works.
appropriate).
Fixes a change that broke the documentation site builds.
> chore: fix broken imports

- docs/keto/guides/migrating-legacy-policies.mdx
- docs/keto/guides/upgrade.mdx
- package.json
- src/sidebar.js
the changes.
works.
appropriate).
> fix: added migrate-legacy-policies guide closes #634

- docs/guides/cli/05_cli-basics.mdx
- docs/guides/cli/15_config-identity-service.mdx
the changes.
works.
appropriate).
Added documentation on importing/exporting configuration which currently applies to Identity / Kratos. As such this is labeled `Configure Identity Service`.
Additionally, updated the existing `CLI basics` document as it didn't contain information about creating projects through the CLI.
> docs: Document importing / exporting Identity (Kratos) configs through the CLI

- docs/ecosystem/community.md
Adds blog posts contributed by the community on the ory blog to the community articles / projects. 
preparation for update of community page :soon:
the changes.
works.
appropriate).
> docs: add guest posts to community articles

- docs/kratos/concepts/email-sms.md
This is the documentation update related to [#2351](https://github.com/ory/kratos/pull/2351)
the changes.
works.
appropriate).
> docs: certificate based authentication for smtp client

- docs/hydra/guides/oauth2-grant-type-jwt-bearer.mdx
Added documentation describing how to setup trust relationships that allow signing tokens for any subject.
ory/hydra#3012
the changes.
works.
appropriate).
> docs: add docs for trust grants with any subject

- docs/hydra/configure-deploy.mdx
the changes.
works.
appropriate).
> fix: updated logs for hydra guide. closes #750

- docs/kratos/guides/sign-in-with-github-google-facebook-linkedin.mdx
Added documentation describing how to add NetID as Social Identity Provider to Kratos.
This is a complement to https://github.com/ory/kratos/pull/2394 and should be merged after linked PR.
the changes.
works.
appropriate).
> feat: add documentation for setting up NetID provider

- code-examples/protect-page-login/go/middleware.go
- code-examples/protect-page-login/php/app.php
the changes.
works.
appropriate).
> fix: fixed urls for protect page guides. Closes #758

- docs/oathkeeper/pipeline/mutator.md
the changes.
works.
appropriate).
> fix: added warning message for hydrator mutator

- vercel.json
I found this route through random search result and it leads to 404 atm.
> fix: add missing redirect

- docs/oathkeeper/guides/upgrade.mdx
- src/sidebar.js
the changes.
works.
appropriate).
> docs: oathkeeper upgrade guide

- docs/hydra/guides/oauth2-public-spa-mobile.mdx
Fixed minor typo in note block
> Update oauth2-public-spa-mobile.mdx to fix minor typo

- .github/workflows/spellchecker.yml
- adds a spellcheck for US spelling to the CI, checks only .md/.mdx files in /docs.
- it does not fail when there is mistakes, but we should change that once the current misspellings are fixed.
the changes.
works.
appropriate).
> feat: spellchecker CI

- docs/guides/manage-identities/import-identity.mdx
- docs/guides/manage-identities/managing-users-identities.mdx
- src/sidebar.js
- vercel.json
the changes.
works.
appropriate).
One of the docs was featured both in Kratos/admin (as the only doc) and in guides/manage-identities (where other docs from kratos/admin were moved). Moved the doc, removed the "Admin" category in Kratos, added a redirect to vercel.json.
> Moved document from Kratos/admin to guides/manage-identities

- docs/kratos/concepts/index.md
the changes.
works.
appropriate).
correct to "self-service" which match in terminology (https://www.ory.sh/docs/kratos/concepts/terminology#self-service)
> docs: correct term to terminology

- docusaurus.config.js
- src/sidebar.js
the changes.
works.
appropriate).
Moved the docs that talk specifically about open source and contribution-related topics to top navbar. Adjusted sidebars to accommodate two separate sidebars. Added a top navbar button that allows to quickly return to the documentation.
> feat: Move "Contributing & Open Source" docs to top navbar

- docusaurus.config.js
the changes.
works.
appropriate).
> fix: move sidebar

- docs/guides/_common/ory-cli.mdx
- docs/guides/protect-page-login/expressjs.mdx
- docs/guides/protect-page-login/go.mdx
the changes.
works.
appropriate).
Updated the reusable Ory CLI snippet used across the `protect page with login` examples to explain the role of the proxy in a simpler way and to refer to the recently added CLI proxy/tunnel documentation.
> docs: update ory cli description for protect page with login guides

- src/theme/Footer/index.js
the changes.
works.
appropriate).
> style: center align footer

- tests/playwright/protect-page-login.spec.ts
the changes.
works.
appropriate).
> fix: playwright tests

- docs/kratos/guides/tracing.mdx
This PR updates the documentation around tracing for Ory Kratos. Ref: https://github.com/ory/kratos/pull/2318
the changes.
works.
appropriate).
> docs(kratos): update info on tracing

- docs/guides/manage-identities/managing-users-identities-metadata.mdx
- src/sidebar.js
the changes.
works.
appropriate).
> docs: add identity metadata documentation

- docs/guides/custom-domains.mdx
- src/sidebar.js
the changes.
works.
appropriate).
> feat: make cors more visible

- docs/kratos/concepts/credentials.mdx
the changes.
works.
appropriate).
> Fix typo in kratos/credentials.mdx

- docs/oathkeeper/pipeline/authn.md
the changes.
works.
appropriate).
> fix: added documentation for additional_headers

- docs/oathkeeper/pipeline/mutator.md
the changes.
works.
appropriate).
> chore: fix broken note box

- docs/guides/customize-identity-schema.mdx
the changes.
works.
appropriate).
> docs: update notice on identity metadata

- docs/kratos/reference/configuration-editor.mdx
the changes.
works.
appropriate).
> fix: fixed configuration-editor for kratos

- docs/ecosystem/community.md
- docs/oathkeeper/pipeline/authn.md
- adds the unofficial laravel sdk to community docs
thanks @ALTELMA 🙇 
the changes.
works.
appropriate).
> docs: add laravel unofficial sdk

- docs/kratos/quickstart.mdx
the changes.
Just a grammar fix.
> fix: grammar on Kratos quick-start referencing out dated routes

- docs/kratos/concepts/email-sms.md
Docs for new `local_name` config parameter introduced in https://github.com/ory/kratos/pull/2445
https://github.com/ory/kratos/pull/2445
the changes.
works.
appropriate).
> docs: kratos courier local_name

- docs/kratos/guides/retrieve-social-sign-in-access-refresh-id-token.md
the changes.
works.
appropriate).
> chore: fix typo

- docs/guides/protect-page-login/nextjs.mdx
it was unclear where this route file should be in the docs tutorial. 
it is clear in the blogpost and also when looking at the example code, but this led to some confusion for users.
the changes.
works.
appropriate).
> fix: add small detail nextjs guide

- docs/guides/social-signin/overview.mdx
the changes.
works.
appropriate).
> fix: update account linking-related content

- docs/ecosystem/community.md
fixes a broken link
the changes.
works.
appropriate).
> docs: fix link

- docs/kratos/guides/deploy-kratos-example.mdx
the changes.
works.
appropriate).
> fix: fix broken link on master

- docs/keto/guides/rbac.mdx
the changes.
works.
appropriate).
> fix: Fixed formatting for RBAC guide

- docs/security-model.mdx
the changes.
works.
appropriate).
> docs: update jwt and cors help

- docs/ecosystem/security.md
as discussed in https://github.com/ory/web/pull/686/
> docs: update security policy with private bug bounty program infos

- package.json
the changes.
works.
appropriate).
> fix: format

- docs/welcome.mdx
Hi 👋 
I wasn't entirely sure if in this case we would prefer to use the name `OAuth2` (as in the rest of the page) or `OAuth 2.0` (as in the linked concept page).
I didn't find a related ticket.
> docs: fix anchor text typo to OAuth 2.0 concept page

- docs/guides/protect-page-login/vue.mdx
> chore: review and edits

- docs/ecosystem/community.md
@tinco Thanks for sharing this! 
Do you think the description is accurate? 
Further would you be up to contribute this to our [new community example repository](https://github.com/ory/examples) - then we can maintain it down the line and give it some more exposure.
In any case thanks for being a part of the Ory community!
> docs: fly.io example config

- docs/guides/cli/17_configure-permission-service.mdx
> fix: use consistent sidebar ordering

- docs/hydra/debug.mdx
the changes.
works.
appropriate).
> docs(hydra): remove legacy error setting

- docs/kratos/concepts/messages.json
This is the output of the change `writeMessagesJson` function in https://github.com/ory/kratos/pull/2519.
> add kratos messages.json

- src/pages/_assets/examples-content.tsx
- adds the new vue example
- correct language / title for next.js ect.
- adds 2 missing examples from ory/examples
> fix: update example page

- docs/guides/social-signin/dingtalk.mdx
Simple formatting fixes for the recently added DingTalk social sign-in guide.
> chore: fix dingtalk formatting

- docs/kratos/concepts/ui-user-interface.mdx
> docs: add messages to docs

- docs/ecosystem/community.md
- src/pages/_assets/examples-content.tsx
> fix: add kratos/hydra integration example

- vercel.json
This PR removes one of the redirects added in the "documentation cleanup" PR. Why? The document for which the redirect was created was supposed to be scrapped, but in the end, we kept it in and just updated the content.
> chore: remove unnecessary redirect

- docs/ecosystem/versioning.md
https://github.com/ory/kratos/releases/tag/v0.10.0
> chore: update kratos to incubating

- docs/kratos/quickstart.mdx
> fix: broken configuration url paths

- docs/ecosystem/community.md
> docs: add community article

- docs/guides/social-signin/github.mdx
This PR updates the GH social sign-in provider integration guide with information about adding integration through a GitHub app.
> docs: update the GitHub social sign-in integration guide

- .prettierignore
> chore: add next and test reports to prettierignore

- .github/workflows/format.yml
CI displays missing formatting. Currently that's in black and white. This PR makes it show up in color.
> Display missing formatting in color

- docs/concepts/emails.mdx
> docs(cloud): update sending emails section

- docs/keto/performance.mdx
> fix: typo in performance

- docs/guides/social-signin/data-mapping.mdx
Please do not merge before related changes are live.
https://github.com/ory/kratos/pull/2569/commits/e73f9f037ac54a17d8526a7c4001cd7dc052808a
https://github.com/ory/kratos/issues/2552
- [ X ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ X ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ X ] I have read the [security policy](../security/policy).
- [ X ] I confirm that this pull request does not address a security vulnerability. 
- [ X ] I have added tests that prove my fix is effective or that my …
> chore: add documentation for mapping metadata

- docs/kratos/self-service.mdx
- docs/welcome.mdx
> docs: update intro

- docs/guides/social-signin/apple.mdx
apparently there is something missing in the apple provider example config
- https://ory-community.slack.com/archives/C012RJ2MQ1H/p1656683130247169?thread_ts=1656473376.933289&cid=C012RJ2MQ1H
- https://ory-community.slack.com/archives/C012RJ2MQ1H/p1658225513973659?thread_ts=1658223848.090699&cid=C012RJ2MQ1H
> docs: apple social login

- docs/keto/guides/rbac.mdx
Currently this page is broken https://www.ory.sh/docs/keto/guides/rbac
> fix: admoniton termination

- docs/guides/mfa/01_overview.mdx
- docs/guides/mfa/05_strict_lax.mdx
- docs/guides/mfa/10_request_2fa.mdx
- docs/guides/mfa/15_totp.mdx
- docs/guides/mfa/20_webauthn.mdx
- docs/guides/mfa/25_lookup_secrets.mdx
A few quick fixes for the MFA topic - updated formatting and a few headings.
> chore: mfa docu fixes

- docs/hydra/guides/token-expiration.mdx
> docs: remove unreleased feature

- .github/workflows/playwright.yml
This PR fixes the failing Playwright tests by using a newer version of the related GHA.
> chore: ci fix

- docs/welcome.mdx
Hyphenate "open source" when used as an adjective preceding a noun in the intro doc. Why? ➡️https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/o/open-source
> chore: hyphenate open source in intro

- README.md
As described in https://github.com/ory/docs/pull/918#discussion_r925611963 this documents it.
> docs: document list style

- docs/guides/social-signin/apple.mdx
- docs/guides/social-signin/auth0.mdx
- docs/guides/social-signin/data-mapping.mdx
- docs/guides/social-signin/dingtalk.mdx
- docs/guides/social-signin/discord.mdx
- docs/guides/social-signin/facebook.mdx
- docs/guides/social-signin/generic.mdx
- docs/guides/social-signin/get-tokens.mdx
- docs/guides/social-signin/github.mdx
- docs/guides/social-signin/gitlab.mdx
- docs/guides/social-signin/google.mdx
- docs/guides/social-signin/microsoft.mdx
- docs/guides/social-signin/netid.mdx
- docs/guides/social-signin/overview.mdx
- docs/guides/social-signin/slack.mdx
- docs/guides/social-signin/spotify.mdx
- docs/guides/social-signin/twitch.mdx
- docs/guides/social-signin/vk.mdx
- docs/guides/social-signin/yandex.mdx
This PR adds more descriptive document titles meant to aid in search engine indexing and discovery of Ory documentation.
Document IDs and filenames remain untouched. I've added the `sidebar_label` metadata and moved the old, short titles there. At the same time, I added longer, more descriptive titles to the `title` metadata.
> docs: add more descriptive titles for social sign in docs

- code-examples/protect-page-login/react/src/App.tsx
> fix: react hook infinite loading

- vercel.json
> chore: fix redirects

- docs/hydra/guides/updating-claims-at-refresh.mdx
Fixes formatting bugs introduced in this PR: https://github.com/ory/docs/pull/932/files
> chore: fix admonition formatting

- vercel.json
This PR adds 3 missing redirects. 
> chore: update redirects list

- docs/hydra/guides/token-expiration.mdx
@tomekpapiernik 
Part of https://github.com/ory/hydra/issues/3157
> docs: document the client custom token lifespan endpoint

- docs/kratos/self-service/hooks.mdx
The current documentation for auth in kratos' web hooks lacks context and is difficult to understand ([example](https://ory-community.slack.com/archives/C012RJ2MQ1H/p1660048260538329)) if you don't know what to look for. This PR adds some context around the snippets and (hopefully) makes this topic a bit clearer.
Also, I removed some stray " (quotation mark) from the path in code snippets on the page.
> docs: add context to hooks auth snippets

- code-examples/protect-page-login/expressjs/routes/index.js
- docs/getting-started/integrate-auth/expressjs.mdx
> fix: incorrect NodeJS guide

- docs/kratos/social-signin/data-mapping.mdx
> chore: fix link

- docs/kratos/concepts/credentials/username-email-password.mdx
- docs/kratos/manage-identities/05_identity-schema.mdx
This removes an old link that stopped making sense + changes the recently added phone number in identity schema bit.
> chore: minor fixes

- docs/hydra/guides/login.mdx
A small change to the doc, the attribute `rememberFor` of the method `acceptLoginRequest` seems to have been changed in the latest node SDK (`rememberFor` instead of `remember_for`).
cf: https://www.ory.sh/docs/hydra/guides/login#operation/getVersion
> fix: typo - HydraAdmin.acceptLoginRequest - remember_for

- docs/guides/integrate-with-ory-cloud-through-webhooks.mdx
- docs/kratos/session-management/05_session-management.mdx
- docs/kratos/social-signin/10_google.mdx
- docs/kratos/social-signin/15_facebook.mdx
- docs/kratos/social-signin/20_microsoft.mdx
- docs/kratos/social-signin/25_github.mdx
- docs/kratos/social-signin/30_apple.mdx
- docs/kratos/social-signin/35_gitlab.mdx
- docs/kratos/social-signin/40_auth0.mdx
- docs/kratos/social-signin/45_slack.mdx
- docs/kratos/social-signin/50_spotify.mdx
- docs/kratos/social-signin/55_discord.mdx
- docs/kratos/social-signin/60_twitch.mdx
- docs/kratos/social-signin/65_netid.mdx
- docs/kratos/social-signin/70_yandex.mdx
- docs/kratos/social-signin/75_vk.mdx
- docs/kratos/social-signin/80_dingtalk.mdx
- docs/kratos/social-signin/90_data-mapping.mdx
This PR updates codeblock language from `json` to `jsonnet` in applicable cases + fixes a typo I found in one of the docs.
https://github.com/ory/docs/issues/971
> chore: update code block language to jsonnet

- docs/kratos/session-management/15_check-session.mdx
X-Session-Token -> X-Session-Cookie
> fix: incorrect header name for session cookies

- docs/keto/sdk/05_go.mdx
In this PR I update two slight bugs on the documentation which prevents the readers from fully following the tutorial.
> docs: updated grpc go sdk documentation

- docs/oathkeeper/pipeline/authn.md
This PR fixes a bug in the Oathkeeper documentation reported here: 
https://ory-community.slack.com/archives/C01340V8KSM/p1661852836606409
> chore: fix oathkeeper 'unauthorized' config example

- vercel.json
Adds a redirect for a document that was removed in the process of docs overhaul.
> chore: add redirect for kratos/index

- docs/getting-started/ory-cloud-oauth2.mdx
- docs/hydra/cli/hydra-janitor.md
- src/sidebar.js
This PR adds a getting started guide for using the Cloud OAuth2 service (Hydra).
https://github.com/ory/docs/pull/981
> docs: add hydra cloud gsg

- docs/kratos/concepts/credentials/username-email-password.mdx
- docs/kratos/manage-identities/25_import-user-accounts-identities.mdx
Added documentation for showing how to import SCrypt algorithm passwords
PR to implement scrypt algorithm importing: https://github.com/ory/kratos/pull/2689
> docs: add guide for importing SCrypt passwords

- docs/getting-started/ory-cloud-oauth2.mdx
- docs/security-model.mdx
This PR updates the `ory get` and `ory update` commands from the GSG to use the `oauth2-config` option introduced in CLI 1.40.
Additionally, the "Security Model" is updated to say that OAuth2 federation is available in Ory Cloud. 
/+ some minor tweaks.
> docs: update hydra docs

- code-examples/auth-api/expressjs/package.json
- code-examples/protect-page-login/expressjs/package.json
- code-examples/protect-page-login/nextjs/package.json
- code-examples/protect-page-login/react/package.json
- code-examples/protect-page-login/vue/package.json
- package-lock.json
- package.json
- src/plugins/docusaurus-plugin-matamo/package.json
Getting everything properly formatted with the latest formatting standard to prepare rolling out formatting checks on CI.
[contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
vulnerability. If this pull request addresses a security. vulnerability, I
the changes.
works.
> chore: update Prettier and ory-prettier-style and format everything

- docs/keto/guides/userset-rewrites.mdx
- docs/keto/reference/ory-permission-language.mdx
- src/sidebar.js
Closes https://github.com/ory/docs/pull/948
> docs: add guide for rewrites

- docs/kratos/social-signin/01_overview.mdx
Made the title more descriptive
> docs: improve social sign in headline

- docs/technical-advisories/01_oidc-redirect-url-cname.mdx
> fix: improve URL for OTA

- docs/getting-started/local-development.mdx
> docs: remove social sign in limitation

- docs/oathkeeper/reference/configuration.mdx
None
closes https://github.com/ory/docs/issues/994
> fix: broken schema link in oathkeeper docs

- docs/hydra/guides/login.mdx
fixes syntax highlighting in docs as well as gender neutral pronouns
> docs: syntax highlighting

- .github/workflows/format.yml
- Makefile
- README.md
- docs/hydra/guides/login.mdx
- package-lock.json
- package.json
Addresses parts of https://github.com/ory-corp/general/issues/735.
> chore: format using Make

- docs/kratos/social-signin/15_facebook.mdx
- package-lock.json
fixes the heading there to be in line with the other guides, e.g.:
https://www.ory.sh/docs/kratos/social-signin/google
> chore: fix heading

- Makefile
> chore: remove double-tabs in Makefile

- docs/kratos/guides/deploy-kratos-example.mdx
127.0.0.1 should be replaced by accounts.example.com within the example diff.
N/a
Just a small change to correct the diff to match the rest of the surrounding diff within the example.
> docs: corrects kratos example diff

- docs/kratos/social-signin/25_github.mdx
> fix: the provider name (Google => Github)

- docs/guides/cli/17_configure-permission-service.mdx
> docs: add guide for Keto commands

- docs/kratos/sdk/01_index.md
Change all kratos sdk from kratos-client to client
> fix: use ory client in sdk docs

- docs/kratos/concepts/credentials/username-email-password.mdx
- docs/kratos/manage-identities/25_import-user-accounts-identities.mdx
PR https://github.com/ory/kratos/pull/2734
https://github.com/ory/kratos/issues/2422
> docs: explain firebase scrypt password hash import

- docs/getting-started/_common/going-to-prod.mdx
- docs/getting-started/integrate-auth/expressjs.mdx
- docs/getting-started/integrate-auth/nextjs.mdx
- docs/getting-started/integrate-auth/php.mdx
- docs/getting-started/integrate-auth/react.mdx
- src/hooks/index.ts
As I've started reading through Ory's docs, I've noticed that quite a few exclamation points are used, sometimes even in consecutive sentences. Of course, this is somewhat of a subjective matter, but in general I'd like to suggest using exclamation points sparingly. I haven't reviewed all the documentation yet, but perhaps this pull request can serve as a starting point.
> docs: remove some exclamation points

- code-examples/protect-page-login/nextjs/pages/index.tsx
Add example of how to get and link to a logout url in nextjs example.
> docs: add logout url example

- docs/keto/guides/userset-rewrites.mdx
The header was a bit broken and I made the guide a bit easier to follow.
> chore: prettify and simplify OPL guide

- docs/getting-started/ory-cloud-oauth2.mdx
Renamed two flags to actual ones, also `--access-token` flag is not needed anymore.
> fix: replace outdated flags with working ones

- docs/getting-started/ory-cloud-oauth2.mdx
One stray PAT mention was left in the guide after the #1031 PR was merged. This PR removes it. 
> chore: remove pat mention after command update

- vercel.json
Fixes the vercel redirect for the recently edited "troubleshooting" document.
> chore: fix troubleshooting redirect

- docs/kratos/manage-identities/20_create-users-identities.mdx
> fix: typo in curl command

- docs/kratos/manage-identities/30_account-recovery.mdx
> docs: add curl for self-hosted

- docs/concepts/cache.mdx
- src/sidebar.js
> docs: add cache docs

- docs/hydra/5min-tutorial.mdx
- docs/hydra/cli/hydra-clients-create.md
- docs/hydra/cli/hydra-clients-get.md
- docs/hydra/cli/hydra-clients-update.md
- docs/hydra/cli/hydra-clients.md
- docs/hydra/concepts/oauth2.mdx
- docs/hydra/debug.mdx
- docs/hydra/debug/csrf.mdx
- docs/hydra/debug/token-endpoint-auth-method.mdx
- docs/hydra/faq.md
- docs/hydra/guides/common-oauth2-openid-connect-flows.mdx
- docs/hydra/guides/cookies.mdx
- docs/hydra/guides/oauth2-clients.mdx
- docs/hydra/guides/oauth2-public-spa-mobile.mdx
- docs/hydra/guides/oauth2-token-introspection.mdx
- docs/hydra/guides/updating-claims-at-refresh.mdx
- docs/hydra/limitations.md
- docs/hydra/security-architecture.md
- docs/hydra/self-hosted/configure-deploy.mdx
- docs/hydra/self-hosted/gitlab.mdx
- docs/hydra/self-hosted/kubernetes-helm-chart.mdx
- docs/hydra/self-hosted/production.md
- docs/hydra/self-hosted/secrets-key-rotation.mdx
This PR collects a bunch of documentation updates that were added to the #874 PR which now has a bunch of conflicts because of how old it is. 
Will add more tweaks here. 
> docs: Hydra documentation updates for v2 release

- docusaurus.config.js
- src/plugins/plugin-usercentrics-gtm/analytics.js
- src/plugins/plugin-usercentrics-gtm/index.js
- src/plugins/plugin-usercentrics-gtm/package.json
Ory switched to Usercentrics as consent management tool. Usercentrics and GTM are included in a new plugin that replaces the previous integration. This also removes the dependency to an external script previously hosted on ory.sh.
> chore: switched consent tool to usercentrics

- docs/kratos/guides/docker.md
This clarifies some of the behavior of the kratos docker image in regards to configuration.
Checklist
> chore: clarify docker documentation for kratos

- docs/getting-started/custom-ui-ory-elements.mdx
- docs/getting-started/custom-ui-preact-ory-elements.mdx
- package-lock.json
- src/sidebar.js
- src/theme/CodeFromRemote.js
- vercel.json
> chore: add more context to code examples used in ory elements guide

- vercel.json
Adds a redirect for an old social sign-in document that's already removed but still comes up in google searches.
> chore: add redirect for removed doc

- docs/hydra/sdk/01_overview.md
- docs/hydra/self-hosted/deploy-hydra-example.mdx
- docs/hydra/self-hosted/upgrade.mdx
- vercel.json
> fix: broken sdk hydra overview

- src/pages/_assets/examples-content.tsx
Just submitted a doc typo fix so most points are moot, I guess. Let me know if I need to do much more.
> docs: correct URL typo in Next.js/React example listing

- .prettierignore
- vercel.json
As reported in https://ory-community.slack.com/archives/C012RJ2MQ1H/p1668027956677509
The redirect was wrong. 
This PR also contains a change to the `.prettierignore` file to ignore the (generated) Keto Protobuf reference.
> fix: recovery docs redirect

- docs/kratos/social-signin/01_overview.mdx
> docs: ory identities does store id tokens now

- docs/hydra/sdk/15_php.mdx
- docs/kratos/social-signin/10_google.mdx
Adds information about required traits for data mapping when adding Google as a social sign-in provider. 
Why? -> https://ory-community.slack.com/archives/C012RJ2MQ1H/p1668022614512459
> docs: add trait info to google social sign-in

- docs/guides/upgrade/01_sdk-v1.mdx
> chore: edit sdk upgrade doc

- docs/ecosystem/deployment.md
- docs/hydra/sdk/15_php.mdx
Closes https://github.com/ory/hydra/issues/3363
> docs: add mysql traditional sql mode

- src/plugins/plugin-usercentrics-gtm/index.js
In order to increase privacy the Google Tag Manager should not be loaded directly form googletagmanager.com. Instead the internal domain sst.ory.sh is preferred.
> chore: switch gtm to internal domain

- code-examples/protect-page-login/nextjs/pages/index.tsx
Missing dependency array for useEffect is causing infinite calls to `/api/.ory/sessions/whoami`. This fixes the issue.
Closes #1006
> docs: update next.js example

- docs/guides/upgrade/01_sdk-v1.mdx
This adds a section to the v1 SDK migration guide for the Keto APIs.
> docs: add v1 SDK migration for Keto

- docs/hydra/self-hosted/configure-deploy.mdx
> doc: fix typo for clients create of hydra

- docs/guides/cli/01_installation.mdx
https://ory-community.slack.com/archives/C010F7Z4XM1/p1669135105694079
> chore: remove proxy docker note

- docs/kratos/session-management/05_session-management.mdx
Original PR https://github.com/ory/kratos/pull/2011/files#diff-a6a02d0df23c798a4830b2cc9df266c6553979544cf5f8400686c4b639637c28
> fix: clarify behavior of self-service session revokation

- docs/kratos/passwordless/05_passkeys.mdx
> chore: fix typos

- docs/hydra/self-hosted/migrating-from-mitreid.mdx
https://ory-community.slack.com/archives/C010F7Z4XM1/p1669755303510639
> chore: fix typoes & spelling in MITREid guide

- docusaurus.config.js
It's pretty annoying to have the usercentrics popup show up when developing locally. This patch disables the popup when previewing the docs locally.
> chore: disable usercentrics on development env

- docs/concepts/password-policy.mdx
- docs/kratos/concepts/credentials/username-email-password.mdx
> feat: password sign in improvements

- docs/kratos/concepts/ui-user-interface.mdx
> fix: typo in the doc

- docs/open-source/commitment.mdx
- src/sidebar.js
> docs: add open source commitment document

- docs/kratos/hooks/01_configure-hooks.mdx
Explain pre and post persist registration webhook.
See https://github.com/ory/kratos/issues/2767
> docs: explain pre and post persist registration webhook

- docs/hydra/self-hosted/deploy-hydra-example.mdx
> fix: replace Kratos by Hydra

- docs/open-source/commitment.mdx
> fix: use headings instead of singular list items

- docs/kratos/self-service/flows/account-recovery-password-reset.mdx
> chore: add missing `RenderFlow` import to recovery docs

- README.md
- docusaurus.config.js
Changes the footer logo URL to take users to ory.sh instead of FB open source pages + minor readme fix.
> fix: change footer logo url

- docs/kratos/manage-identities/25_import-user-accounts-identities.mdx
Cleans up the "importing identities" doc by adding tabs for the different supported hashing formats.
> chore: add tabs for password hashing

- docs/getting-started/ory-network-oauth2.mdx
Removing a statement to avoid misinterpretation.
> chore: update oauth2 quickstart

- docs/kratos/guides/configuring-cookies.mdx
Adding an example for session cookie name configuration.
> docs: add example for session cookie name configuration

- Makefile
- docs/kratos/manage-identities/01_overview.mdx
- docs/kratos/manage-identities/05_identity-schema.mdx
- src/sidebar.js
> docs: update identity schema section

- docs/guides/cli/15_config-identity-service.mdx
- docs/guides/cli/16_configure-oauth2-service.mdx
- docs/guides/cli/17_configure-permission-service.mdx
basically the same document we have for identities and permissions, just with a different sample command at the end.
> docs: configure oauth2 through CLI 

- docs/kratos/concepts/security.mdx
- src/sidebar.js
- fix: threat models doc update
- fix: security section sidebar
- chore: fix typos
- chore: missing feature
> fix: compliance docs update

- docs/hydra/index.md
Use-case centric overview for OAuth2 + OIDC.
> feat: updated OAuth2 overview page

- src/theme/SelfServiceBrowserFlow.js
> docs: update self-service docs diagram

- docs/hydra/sdk/01_overview.md
- docs/keto/sdk/01_overview.md
- docs/kratos/sdk/01_overview.md
- docs/oathkeeper/sdk.md
- docs/sdk.mdx
- package-lock.json
- docs: add elixir sdk
- chore: npm install
> fix: elixir sdk

- code-examples/sdk/go/selfservice/get-active-sessions.go
- code-examples/sdk/go/selfservice/revoke-other-sessions.go
- code-examples/sdk/go/selfservice/revoke-session.go
- code-examples/sdk/go/session/delete-sessions.go
- code-examples/sdk/go/session/disable-session.go
- code-examples/sdk/go/session/get-identity-sessions.go
- code-examples/sdk/go/session/get-session.go
- code-examples/sdk/go/session/get-sessions.go
- code-examples/sdk/go/session/init.go
- code-examples/sdk/typescript/src/selfservice/session/get-active-sessions-native.ts
- code-examples/sdk/typescript/src/selfservice/session/get-active-sessions-react.tsx
- code-examples/sdk/typescript/src/selfservice/session/revoke-other-sessions-native.ts
- code-examples/sdk/typescript/src/selfservice/session/revoke-other-sessions-react.tsx
- code-examples/sdk/typescript/src/selfservice/session/revoke-session-native.ts
- code-examples/sdk/typescript/src/selfservice/session/revoke-session-react.tsx
- code-examples/sdk/typescript/src/session/delete-sessions-native.ts
- code-examples/sdk/typescript/src/session/disable-session-native.ts
- code-examples/sdk/typescript/src/session/get-identity-sessions-native.ts
- code-examples/sdk/typescript/src/session/get-session-native.ts
- code-examples/sdk/typescript/src/session/get-sessions-native.ts
- code-examples/sdk/typescript/src/session/init-client-native.ts
- docs/kratos/session-management/05_session-management.mdx
- Adding self service documentation updates and code examples with the v1 SDK
- Adding admin documentation updates and code examples with the v1 SDK
https://github.com/ory-corp/cloud/issues/3636
> docs: refresh session management documentation

- README.md
Some small tweaks for the guidelines, including a mention of the `slug` metadata.  
> chore: update docu guidelines

- docs/ecosystem/community.md
Adds a link to community.md to a Java reference implementation of a Ory Hydra based login/consent provider.
https://github.com/ardetrick/ory-hydra-refrence-java
N/A: documentation PR.
N/A.
> docs: update community.md to include a Java reference implementation

- vercel.json
This PR adds a redirect for the account recovery document. One of the document ID changes wasn't covered by redirects.
> chore: add redirect for account recovery doc

- docs/ecosystem/contributing.md
- docs/open-source.mdx
- docs/open-source/commitment.mdx
- src/sidebar.js
As described in notion, this updates the documents in the "open source" category.
- rewrite oss overview and add some more important libraries
- move some text from oss overview to commitment document
- add all documents to sidebar
- remove ugly header from contributing
No big changes, but now should be as planned and can improve incrementally from here (contributing.md probably could use an update soonish).
btw also chose to write open source in lower case in all cases. it looks weird when we mix it and as per the [MC guide](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/o/open-source) it should be lowercase (maybe we can add that to our styleguide as well as there are multiple versions in the docs afaik)
If this pull request addresses a security …
> fix: open source category docs

- docs/guides/cli/20_proxy-and-tunnel.mdx
This PR fixes a typo on the Ory Proxy / Ory Tunnel page.
> fix: jwt typo

- docs/kratos/self-service/flows/user-registration.mdx
> fix: outdated issue linked

- docs/kratos/emails-sms/.10_sending-sms.mdx
- docs/kratos/emails-sms/01_sending-emails-smtp.mdx
- docs/kratos/emails-sms/05_custom-email-templates.mdx
- docs/kratos/self-hosted/02_mail-courier-templates.mdx
- docs/kratos/self-hosted/10_sending-sms.mdx
- src/sidebar.js
- vercel.json
Closes https://github.com/ory-corp/cloud/issues/3715
> refactor: email/sms documentation

- docs/ecosystem/community.md
> docs: added hydra golang identity provider example

- docs/keto/index.md
> feat: new permissions introduction

- docs/hydra/self-hosted/configure-deploy.mdx
> chore: format

- .github/CODEOWNERS
- README.md
> chore: add fbolton to codeowners and update readme

- code-examples/protect-page-login/nextjs/package-lock.json
- code-examples/protect-page-login/nextjs/package.json
- code-examples/protect-page-login/nextjs/pages/api/.ory/[...paths].ts
See https://github.com/ory/docs/issues/681#issuecomment-1404668634
> fix: update code example for nextjs

- docs/keto/modeling/create-permission-model.mdx
- src/sidebar.js
This adds a modelling guide for Ory Permissions.
> feat: modelling guide

- docs/troubleshooting/15_magic-link-verification-url.mdx
> docs: add troubleshooting for wrong links in emails

- docs/getting-started/custom-ui-ory-elements.mdx
> feat: add next example to custom ui with elements

- docs/concepts/cache.mdx
> fix: update cache docs

- docs/actions/integrations/mailchimp.mdx
- docs/api/_common/api-types.mdx
- docs/concepts/personal-access-token.mdx
- docs/getting-started/local-development.mdx
- docs/guides/integrate-with-ory-cloud-through-webhooks.mdx
- docs/guides/upgrade/01_sdk-v1.mdx
- docs/hydra/guides/custom-ui-oauth2.mdx
- docs/kratos/manage-identities/10_managing-users-identities-metadata.mdx
- docs/kratos/manage-identities/30_account-recovery.mdx
- docs/kratos/session-management/05_session-management.mdx
- docs/reference/api.json
> docs: rename pat to api key, feature api key info more prominently

- docs/kratos/social-signin/25_github.mdx
As mentioned on Slack (https://ory-community.slack.com/archives/C012RJ2MQ1H/p1676005943037359) updates to link to the most recent version of this code.
> chore: update url

- docs/concepts/cache.mdx
A slight touch-up of the "Edge Sessions" document - fixed feature name, minor tweaks.
> docs: update edge sessions doc

- docs/getting-started/integrate-auth/react.mdx
Got this error while following react login guide.
Changing the flag position solved the error. Raising a PR for the same
- [x ] I have read the [security policy](../security/policy).
> chore: create-react-app flag fix

- docs/kratos/bring-your-own-ui/05_custom-ui-basic-integration.mdx
> fix: custom ui basic integration grammar

- docs/getting-started/integrate-auth/expressjs.mdx
> chore: outdated API snippet

- docs/concepts/cache.mdx
- docs/getting-started/integrate-auth/php.mdx
- docs/kratos/manage-identities/30_account-recovery.mdx
- docs/kratos/sdk/05_go.mdx
- docs/kratos/self-service.mdx
- docs/security-model.mdx
similar to https://github.com/ory/docs/pull/1260 this removes the outdated `V0alpha2Api` in a few more places. SDK docs still need some more love, but this cant hurt :D 
> fix: outdated API snippets

- docs/kratos/bring-your-own-ui/10_custom-ui-advanced-integration.mdx
> fix: advanced integration custom ui docs

- docs/hydra/concepts/consent.mdx
In the `Login Flow` it is clearly stated that:
> The subject must be an immutable user ID, it should never be an email address, a username, or something else that may change over time.
Therefore the `subject` field in the `Consent Challenge Response` should not be an email/username in order to not mislead the reader.
- [x ] I have read the [security policy](../security/policy).
> fix: subject should not be a username/email

- src/css/theme.css
> chore: link color

- docs/kratos/self-service.mdx
Removes `]` from the Form rendering section of Self-service flows.
N/A
> fix: remove stray right square bracket

- docs/kratos/manage-identities/20_create-users-identities.mdx
- docs/kratos/manage-identities/25_import-user-accounts-identities.mdx
- docs/kratos/manage-identities/30_account-recovery.mdx
- docs/kratos/manage-identities/40_invite-users.mdx
- src/sidebar.js
> docs: describe user invite process & cleanup

- docusaurus.config.js
https://github.com/ory/docs/issues/1103
> docs: docs-1103 Automatically delete license headers from code examples

- src/sidebar.js
- vercel.json
- docs: sms doc sidebar
- fix: redirects sms docs
> fix: sms doc

- docs/concepts/cache.mdx
- docs/identities/sign-in/check-session.mdx
> docs: clarify the need for __cflb cookie

- docs/hydra/self-hosted/kubernetes-helm-chart.mdx
It seems if this line is not included, the `hydra-example` pod goes into a `CrashLoopBackOff` state with the following error:
```
level=error msg=Scheme from configuration key `urls.self.issuer` must be `https` when `dev` is `false`. Got scheme in value `http://public.hydra.localhost/` is `http`. To find out more, use `hydra help serve`. audience=application service_name=Ory Hydra service_version=v2.0.3
Error: issuer URL scheme must be HTTPS unless development mode is enabled
issuer URL scheme must be HTTPS unless development mode is enabled
```
> docs: include `hydra.dev=true` in Helm chart quick-start

- docs/kratos/bring-your-own-ui/05_custom-ui-basic-integration.mdx
> docs: typo fixes

- code-examples/curl/registration/submit-registration-api.sh
- code-examples/curl/registration/submit-registration-browser.sh
- code-examples/sdk/typescript/package-lock.json
- code-examples/sdk/typescript/package.json
- code-examples/sdk/typescript/src/selfservice/registration/submit-registration-react.tsx
- docs/guides/integrate-with-ory-cloud-through-webhooks.mdx
- docs/kratos/bring-your-own-ui/05_custom-ui-basic-integration.mdx
> feat: add some documentation for `transient_payload`

- docs/guides/permissions/overview.mdx
- docs/keto/index.md
- src/sidebar.js
> docs: update ory permissions intro

- docs/guides/custom-domains.mdx
- docs/kratos/bring-your-own-ui/20_configure-ory-to-use-your-ui.mdx
Adds information on working with custom domains / base URLs / custom UI paths
> docs: custom domain, custom UI

- docs/kratos/emails-sms/05_custom-email-templates.mdx
- docs/kratos/self-service/flows/account-recovery-password-reset.mdx
- docs/kratos/self-service/flows/verify-email-account-activation.mdx
Closes https://github.com/ory/docs/issues/1276
> feat: add `notify_unknown_recipients` docs

- docs/guides/custom-domains.mdx
- docs/kratos/emails-sms/01_sending-emails-smtp.mdx
Related to https://github.com/ory-corp/cloud/issues/3833
> chore: add notes & troubleshooting for email with CNAMEs

- docs/kratos/bring-your-own-ui/10_custom-ui-advanced-integration.mdx
- docs/kratos/social-signin/10_google.mdx
Documentation for the related PR https://github.com/ory/kratos/pull/3138
It is now possible to configure upstream parameters for OIDC providers. Specifically Google's `login_hint` and `hd` parameters.
> feat: upstream parameters on oidc

- docs/kratos/concepts/ui-user-interface.mdx
> fix: reference to ui partial

- docs/_common/jsonnetwarning.mdx
- docs/kratos/social-signin/83_linkedin.mdx
- src/sidebar.js
see linked PR to add to console UI. 
closes #1247
> docs: login with LinkedIn

- code-examples/migrate-to-ory/1-create-ory-identities.sh
This PR adds admin metadata to imported identities in the script from the Auth0 guide.
> feat: add admin metadata to imported identities for attribution

- docs/guides/cli/05_cli-basics.mdx
I believe the `n` is supposed to be a `y`.
> Minor CLI instructions fix

- docs/hydra/concepts/before-oauth2.mdx
- docs/hydra/guides/client-token-expiration.mdx
- docs/hydra/guides/oauth2-clients.mdx
- docs/hydra/guides/oauth2-token-introspection.mdx
- docs/hydra/jwks.md
- docs/oauth2-oidc/authorization-code-flow.mdx
- docs/oauth2-oidc/client-credentials.mdx
- docs/oauth2-oidc/index.md
- docs/oauth2-oidc/jwt-access-token.mdx
- docs/oauth2-oidc/overview/oauth2-concepts.mdx
- docs/oauth2-oidc/overview/oidc-concepts.mdx
- docs/oauth2-oidc/refresh-token-grant.mdx
- docs/oauth2-oidc/userinfo-oidc.mdx
> docs: perform OAuth2 doc review by fintan

- docs/cli.mdx
- vercel.json
Closes https://github.com/ory/docs/issues/1344
> chore: remove empty docs/cli page

- docs/oauth2-oidc/custom-login-consent/flow.mdx
> docs: describe how to handle skip consent in custom UI

- docs/kratos/bring-your-own-ui/15_custom-ui-ory-elements.mdx
Improve documentation on Ory Elements examples
> fix: elements examples

- docs/guides/integrate-with-ory-cloud-through-webhooks.mdx
- docs/guides/permissions/overview.mdx
- docs/hydra/guides/jwt.mdx
- docs/keto/modeling/create-permission-model.mdx
- docs/kratos/bring-your-own-ui/05_custom-ui-basic-integration.mdx
- docs/kratos/bring-your-own-ui/10_custom-ui-advanced-integration.mdx
- docs/kratos/bring-your-own-ui/15_custom-ui-ory-elements.mdx
- docs/kratos/emails-sms/01_sending-emails-smtp.mdx
- docs/kratos/hooks/01_configure-hooks.mdx
- docs/kratos/manage-identities/15_customize-identity-schema.mdx
- docs/kratos/self-service/flows/account-recovery-password-reset.mdx
- docs/kratos/social-signin/05_generic.mdx
- docs/kratos/social-signin/10_google.mdx
- docs/kratos/social-signin/15_facebook.mdx
- docs/kratos/social-signin/20_microsoft.mdx
- docs/kratos/social-signin/25_github.mdx
- docs/oauth2-oidc/authorization-code-flow.mdx
- docusaurus.config.js
This PR updates the docusaurus config to display H4s in the right-hand side ToC by default, w/o the need to add metadata to the frontmatter. As this is now the case, the existing frontmatter metadata that facilitated this is removed.
> feat: update global config to show h4 in toc by default

- code-examples/sdk/typescript/src/selfservice/logout/express.ts
If I didn't mess anything up, this should fix https://github.com/ory/docs/issues/1234. 
> fix: typescript logout example

- README.md
Adds a tip for dealing with headings, partials, and the ToC. 
> docs: update guidelines with a partials tip

- docs/ecosystem/sqa.md
Fix url anonymizer and update sqa page payload data sent
[PR](https://github.com/ory/x/pull/681)
> fix: sqa page metrics

- docs/security-model.mdx
> docs: update security-model.mdx

- docs/kratos/social-signin/20_microsoft.mdx
> fix: reword section `Selecting a Tenant` to indicate the options are alternatives

- docs/kratos/manage-identities/25_import-user-accounts-identities.mdx
Overrides the site-wide config and makes h3 the lowest heading "size" added to the ToC.
> fix: toc heading visibility

- docs/identities/sign-in/actions.mdx
- docs/kratos/self-service/flows/user-settings.mdx
- docs/kratos/self-service/flows/verify-email-account-activation.mdx
Closes https://github.com/ory/docs/issues/1338
> feat: add documentation for showing verification after registration

- docs/kratos/emails-sms/05_custom-email-templates.mdx
> fix: typo (Spring —> Sprig)

- docs/actions/integrations/hubspot.mdx
- Changes placeholder name from "api key" to "private app access token" for clarity
- Fixes example to show config that triggers the hook after social profile registration. 
- Other small tweaks including rewording and shortening the intro.
> docs: update hubspot integration doc

- src/components/Install/MacOS.tsx
Replace `cli help` with `ory help`
> docs: wrong cli command

- docs/security-compliance/compliance-and-certifications.md
- src/sidebar.js
As Ory has just received ISO 27001 certification, it makes sense for us to have a dedicated "Compliance and certification" page to keep track of our certifications in the docs.
> docs: added new Compliance and certifications page

- docs/hydra/self-hosted/deploy-hydra-example.mdx
Fixes hydra self hosting/deploying documentation
This pull request relates to the documentation for deploying a self hosted hydra instance.
1) Fixes 404 error in "[Install Ory Hydra](http://localhost:3000/docs/hydra/self-hosted/deploy-hydra-example#install-ory-hydra)" step 3
Before (404 error):
`wget https://github.com/ory/hydra/releases/download/v2.1.1/hydra_v2.1.1-linux_64bit.tar.gz`
After:
`wget https://github.com/ory/hydra/releases/download/v2.1.1/hydra_2.1.1-linux_64bit.tar.gz`
2) Updated the `location` blocks of the nginx server configuration to account for the new admin endpoints, and adds the …
> docs: update self hosted hydra deploy docs for hydra 2.x

- docs/getting-started/integrate-auth/01_go.mdx
> chore: update console label

- .vscode/tasks.json
- docs/kratos/social-signin/96_native-apps.mdx
- package-lock.json
- package.json
- src/sidebar.js
- src/theme/CodeFromRemote.module.css
- src/theme/CodeFromRemote.tsx
> docs: describe OIDC for native apps

- docs/kratos/social-signin/96_native-apps.mdx
11. Browser sends authorization code to Kratos
12. Kratos responds to the browser
13. Browser initialize return to the application
> fix: native apps flow chart browser native interaction

- docs/kratos/social-signin/96_native-apps.mdx
> fix: social signin http return code

- docs/actions/integrations/mailchimp.mdx
> docs: mailchimp guide

- docs/kratos/social-signin/96_native-apps.mdx
> chore: remove duplicate h1

- docs/kratos/mfa/01_overview.mdx
- docs/kratos/mfa/20_webauthn-fido-yubikey.mdx
> docs: minor changes MFA

- docs/kratos/bring-your-own-ui/15_custom-ui-ory-elements.mdx
> chore: correct npm package

- .github/workflows/playwright.yml
- code-examples/protect-page-login/flutter_web_redirect/.gitignore
- code-examples/protect-page-login/flutter_web_redirect/README.mdx
- code-examples/protect-page-login/flutter_web_redirect/lib/main.dart
- code-examples/protect-page-login/flutter_web_redirect/lib/services/auth.dart
- code-examples/protect-page-login/flutter_web_redirect/pubspec.lock
- code-examples/protect-page-login/flutter_web_redirect/pubspec.yaml
> fix: flutter example with latest ory sdk

- docs/identities/sign-in/actions.mdx
> fix: show_verification_ui hook docs

- docs/kratos/self-service/flows/user-login.mdx
- docs/kratos/self-service/flows/user-registration.mdx
- docs/kratos/self-service/flows/user-settings.mdx
- src/theme/SelfServiceBrowserFlow.js
adds new browser flow diagram, as discussed here: https://github.com/ory/docs/pull/1175#issuecomment-1541460252 
also removes some instances of "Flow UI" in the text.
> fix: new selfservice diagram

- docusaurus.config.js
> feat: chatbot integration

- docs/keto/sdk/10_python.mdx
- src/sidebar.js
- chore: format
- chore: format
- fix: add to sidebar
> fix: add python sdk example to sidebar

- docs/guides/integrate-with-ory-cloud-through-webhooks.mdx
just making this comment more clear.
> fix: clarify comment

- docs/self-hosted/kratos/configuration/oidc.mdx
- fix some broken links in the social signin doc for selfhosted
- add example config 
- rephrase some things to be less confusing.
> fix: self-hosted social signin docs

- docs/keto/sdk/10_python.mdx
- docs/kratos/manage-identities/25_import-user-accounts-identities.mdx
- Clarify the requirements necessary to import hashed passwords from anywhere else.
- Improve the firebase import documentation specifically. This recommendation was found in slack and I've also tried it for a project successfully.
- Ran format for the whole repository that fixed things unrelated to my change.
> docs: improve general import documentation as well as firebase specifically

- docs/keto/guides/simple-access-check-guide.mdx
Removes some fluff from the keto guide (mostly fluff from intro/outro) and fixes some common style errors.
> fix: keto guide style

- docs/guides/cli/20_proxy-and-tunnel.mdx
- docs/security-model.mdx
> chore: add tunnel to the security model

- docs/kratos/bring-your-own-ui/10_custom-ui-advanced-integration.mdx
Relates to the feature added here https://github.com/ory/kratos/pull/3276
- https://github.com/ory/kratos/pull/3276
- https://github.com/ory/kratos/issues/2709
> feat: add documentation for upstream parameter 'prompt'

- docs/kratos/passwordless/01_webauthn.mdx
> chore: add a note on updating webauthn configs

- docs/guides/integrate-with-ory-cloud-through-webhooks.mdx
> docs: add webhooks source ips

- docs/guides/gitops.mdx
- src/sidebar.js
Add a short guide that explains how to version and track Ory Network configuration in git with example for 
> docs: gitops guide

- docs/keto/guides/expand-api-display-who-has-access.mdx
> fix: use master branch for keto examples

- docs/oauth2-oidc/issuer-url.mdx
- src/sidebar.js
> docs: add issuer url docs

- docs/oauth2-oidc/issuer-url.mdx
> chore: fix broken link

- docs/hydra/self-hosted/deploy-hydra-example.mdx
fixes a stray codeblock that was introduced in https://github.com/ory/docs/pull/1409
> fix: hydra example broken codeblock

- docs/kratos/self-service/flows/user-login.mdx
- docs/kratos/self-service/flows/user-registration.mdx
> fix: remove outdated notice

- docs/kratos/passwordless/01_webauthn.mdx
closes https://github.com/ory-corp/cloud/issues/2620
> fix: console ui tab

- docs/kratos/social-signin/55_discord.mdx
This PR adds an argument to the command example of encoding Discord config into base64. This addition outputs the encoded data as a single line, makes it easier to copy paste into the Kratos config.
> Small addition to base64 command

- docs/kratos/social-signin/55_discord.mdx
> Revert "Small addition to base64 command"

- docs/kratos/guides/deploy-kratos-example.mdx
Example secrets are longer than 32 characters, so if you try to deploy it, kratos will fail.
Also updated the openssl code to generate secrets with 32 characters. Current script generates string longer than 32 characters.
> docs: update deploy-kratos-example.mdx

- docs/oauth2-oidc/complex-identity-flows.mdx
- docs/oauth2-oidc/identity-provider-integration-settings.mdx
- src/sidebar.js
> feat: persisting OAuth2 login across Identity flows

- docusaurus.config.js
> fix: disable user centrics

- docusaurus.config.js
> fix: navbar links

- docusaurus.config.js
Kapa.ai is a nice tool but the bundle size is way too big, dragging down page speed significantly. Until the Kapa.ai widget is optimized, or we find a way to lazy load the script, we need to disable it.
> fix: disable kapa.ai

- docs/ecosystem/upgrading.md
> docs: kratos v1 graduated

- docs/kratos/bring-your-own-ui/20_configure-ory-to-use-your-ui.mdx
We've added the capability to disable Account Experience's welcome screen. This adds a note in the docs for it.
> feat: add ability to disable the AX welcome screen

- docs/guides/integrate-with-ory-cloud-through-webhooks.mdx
> chore: add actions docs

- docs/hydra/self-hosted/gitlab.mdx
Fixed multiple spelling mistakes and some Denglish :-)
> fix: spelling mistakes in /docs/hydra/self-hosted/gitlab

- docusaurus.config.js
> fix: image width and height

- docs/kratos/self-service.mdx
Closes https://github.com/ory/kratos/issues/2043
> docs: update headline

- docs/kratos/passwordless/01_webauthn.mdx
> docs: update docs example for multiple webauthn origins

- docs/kratos/self-service/flows/account-recovery-password-reset.mdx
Adds example identity schema for fallback recovery address
also cleans up the doc a bit and removes some words without changing the meaning
> docs: fallback recovery address

- docs/getting-started/integrate-auth/10_expressjs.mdx
added title to code block to make it clear which file is touched
> fix: update 10_expressjs.mdx

- docs/kratos/guides/docker.md
closes https://github.com/ory/docs/issues/1302
> fix: docker custom image

- docs/kratos/mfa/01_overview.mdx
- docs/kratos/mfa/05_step-up-authentication.mdx
language around dynamic MFA for SEO
> fix: add a bit of language around dynamic MFA for SEO

- docs/kratos/social-signin/96_native-apps.mdx
Fix blank code boxes by using the master as a base.
> fix: code examples branch

- docs/kratos/concepts/security.mdx
Adds description of automated attack / bot protection and polishes the doc overall a bit.
closes https://github.com/ory-corp/general/issues/869
> docs: bot attack protection

- docs/getting-started/integrate-auth/25_react.mdx
fixed line to create new react project, so it's really created as a TS project (the --typescript option is wrong)
> fix: update 25_react.mdx

- src/sidebar.js
- vercel.json
- fix: sidebar orphan
- fix: remove empty doc
Fixes two of the orphaned pages, more after this is merged @kmherrmann 
> fix: page orphans

- vercel.json
added redirects for broken links
> fix: added redirects for broken links (Part 1)

- docs/kratos/social-signin/30_apple.mdx
> fix: update apple guide

- README.md
Documents how to navigate the user to console pages in the docs.
> fix: add console current to styleguide

- docs/kratos/manage-identities/25_import-user-accounts-identities.mdx
closes https://github.com/ory/docs/pull/1505
> docs: batch create identities

- docs/ecosystem/projects.mdx
> docs: add headlines for TOC to self-hosting

- docs/troubleshooting/30_iframes.mdx
> docs: add iframe debug

- docs/concepts/cache.mdx
> docs: update latencies

- docs/kratos/self-service/flows/verify-email-account-activation.mdx
> fix: document how to carry over verified emails

- docs/keto/concepts/01_relation-tuples.mdx
This PR is to fix a copy-paste mistake in the documentation.
> docs: fixed graphical representation of the example

- docs/hydra/security-architecture.md
> docs: update crypto docs

- docs/kratos/social-signin/30_apple.mdx
Added info on "Add the identifier of the Services ID", that this is also not the name
> fix: update 30_apple.mdx

- docs/identities/sign-in/social-sign-in/redirect-url.mdx
> chore: fix code comment

- docs/troubleshooting/35_oauth2-trust-audience.mdx
Closes https://github.com/ory/network/issues/299
> docs: how to deal with oauth2 audience mismatch

- docs/kratos/passwordless/06_code.mdx
> chore: mark one-time code as preview

- code-examples/protect-page-login/react/package-lock.json
- code-examples/protect-page-login/react/package.json
- code-examples/protect-page-login/react/src/App.tsx
- docs/getting-started/integrate-auth/25_react.mdx
> docs: improve react guide

- docs/guides/gitops.mdx
> chore: fix update opl command

- src/components/Install/MacOS.tsx
By using the  variable, we can show
Usage:
kratos [command]
Available Commands:
cleanup     Various cleanup helpers
completion  Generate the autocompletion script for the specified shell
courier     Commands related to the Ory Kratos message courier
delete      Delete resources
format      Helpers for formatting code
get         Get resources
hashers     This command contains helpers around hashing
help        Help about any command
import      Import resources
lint        Helpers for linting code
list        List resources
migrate     Various migration helpers
remote      Helpers and management for remote Ory Kratos instances
serve       Run the Ory Kratos server
validate    Validate resources
version     Show the build version, build time, and git hash
Flags:
-h, --help   help for …
> fix: ory should not be hardcoded

- code-examples/sdk/typescript/src/session/whoami-jwt.ts
- docs/identities/session-to-jwt-cors.mdx
- src/sidebar.js
> docs: using the session to JWT feature

- docs/ecosystem/changelog.md
> chore: update changelog doc

- docs/identities/session-to-jwt-cors.mdx
- docs/kratos/session-management/01_overview.mdx
> fix: jwt docs

- docs/ecosystem/community.md
> fix: add community project

- docs/kratos/bring-your-own-ui/10_custom-ui-advanced-integration.mdx
> feat: add docs for auth_type upstream param

- code-examples/sdk/dart/social-sign-in/sign-in-with-google.dart
- docs/kratos/social-signin/10_google.mdx
- docs/kratos/social-signin/30_apple.mdx
- docs/kratos/social-signin/96_native-apps.mdx
> feat: add documentation for native Google SDK social sign in

- docs/kratos/emails-sms/01_sending-emails-smtp.mdx
> fix: delivery_method key in HTTP courier docs

- docs/kratos/organizations/organizations.mdx
> chore: text bug

- docusaurus.config.js
> chore: ai modal title

- docs/keto/reference/ory-permission-language.mdx
removes mention of a planned feature that is not yet implemented. we should rather use issues/design docs for upcoming features and just document things that are implemented and working.
> fix: text bug

- docs/concepts/password-policy.mdx
- docs/getting-started/oauth2-openid/expressjs.mdx
- docs/getting-started/ory-network-oauth2.mdx
- docs/guides/gitops.mdx
- docs/hydra/5min-tutorial.mdx
- docs/hydra/self-hosted/gitlab.mdx
- docs/hydra/self-hosted/kubernetes-helm-chart.mdx
- docs/identities/model/manage-identity-schema.mdx
- docs/kratos/concepts/credentials/username-email-password.mdx
- docs/kratos/social-signin/09_ory.mdx
- docs/oauth2-oidc/client-credentials.mdx
> fix: quote bash variables

- docs/kratos/bring-your-own-ui/10_custom-ui-advanced-integration.mdx
> chore:  text bug

- docs/kratos/session-management/25_revoke-sessions-hook.md
The path in the example code was incorrect
> fix: revoke_sessions_hook path

- docs/guides/cli/20_proxy-and-tunnel.mdx
I've experienced troubles while setting up the tunnel and found out I was not the only one failing in doing so (see [slack](https://ory-community.slack.com/archives/C02MR4DEEGH/p1690126764132889)) so I've suggested updating the documentation accordingly. 
> fix: ory tunnel project slug parameter

- docs/actions/session.mdx
- docs/troubleshooting/11_actions.mdx
Documents how to resolve a common Ory Actions issue. 
It was a bit hard to find so I created a dedicated document for common troubleshooting advice for Ory Actions.
> fix: actions troubleshooting

- docs/kratos/self-hosted/15_mfa.mdx
> fix: change `required_all` to `required_aal` in self-hosted kratos mfa guide

- docs/kratos/manage-identities/25_import-user-accounts-identities.mdx
Adds documentation for importing identities with HMAC-hashed passwords
- https://github.com/ory/kratos/pull/3544
> feat: Added documentation for HMAC identity import

- docs/concepts/password-policy.mdx
> fix: patch min password length Parte Deux

- docs/api/eventual-consistency.mdx
> fix: rectify docs

- docs/kratos/emails-sms/01_sending-emails-smtp.mdx
> fix: semantics config

- docs/kratos/social-signin/10_google.mdx
- docs/kratos/social-signin/30_apple.mdx
> docs: document additional_id_token_audiences

- docs/kratos/social-signin/10_google.mdx
> fix: change default for `email_verified` to `false` in Google jsonnet

- docs/identities/session-to-jwt-cors.mdx
> docs: explain how to export public key from JWKS

- docs/hydra/guides/updating-claims-at-refresh.mdx
> fix: token_hook example

- docs/concepts/cache.mdx
> fix: console instructions for edge sessions

- docs/kratos/social-signin/05_generic.mdx
> feat: document claims source

- docs/oauth2-oidc/revoke-consent.mdx
- docs/oauth2-oidc/skip-consent.mdx
- src/sidebar.js
> docs: explain skip (logout) consent

- docs/guides/custom-domains.mdx
> docs: add note for cf release zone

- docs/oauth2-oidc/issuer-url.mdx
> docs: clarify issuer URL changes

- docs/kratos/concepts/ui-user-interface.mdx
2. is a fix for a previously unknown bug, explain the bug and how to reproduce it in this pull request;
You can see the 404 for the broken link slightly down the page [here](https://www.ory.sh/docs/kratos/concepts/ui-user-interface#checkbox-input-node)
Needed this example for my own custom SSR flow with a checkbox & figured I could help someone else find it faster.
> fix: broken link for example of server side rendered checkbox

- docs/concepts/cache.mdx
> fix: add edge session lifetime

- docs/kratos/social-signin/20_microsoft.mdx
> docs: update microsoft guide

- docs/identities/sign-in/actions.mdx
fix: Adjust the document hyperlink order to correct
> fix: update actions.mdx

- docusaurus.config.js
> fix: copilot label

- docs/kratos/emails-sms/05_custom-email-templates.mdx
> fix: email template formatting & wording

- docs/kratos/social-signin/83_linkedin.mdx
> feat: document linkedin v2

- docs/kratos/quickstart.mdx
https://github.com/ory/kratos/issues/3828
> fix: use master instead of tag for docker-compose

- docs/guides/rate-limits.mdx
> docs: update plan names

- docs/hydra/self-hosted/ssl-https-tls.mdx
- **fix: copilot label**
- **fix: clarify TLS default hydra selfhosted**
> fix: clarify tls not enabled by default self-hosted Hydra

- docs/self-hosted/operations/15_observability.md
Fix hydra prometheus endpoint on the Obervability page, overlooked by https://github.com/ory/docs/pull/1374.
- https://github.com/ory/hydra/issues/3468
> fix: hydra prometheus link in docs

- docs/concepts/personal-access-token.mdx
> docs: clarify token use

- docs/oauth2-oidc/jwt-access-token.mdx
> fix: clarify default jwks

- docs/kratos/self-hosted/03_mail-courier-http.mdx
Update the variables in the sample jsonnet code. The outdated code would lead the reader to wrongly set Kratos HTTP courier.
> fix: update kratos http courier jsonnet template sample

- docs/guides/integrate-with-ory-cloud-through-webhooks.mdx
- docs/guides/ip-allowlist.mdx
- src/sidebar.js
> chore: update Ory Network IP addresses documentation

- docs/guides/integrate-with-ory-cloud-through-webhooks.mdx
> fix: broken admonition

- docs/getting-started/local-development.mdx
> fix: explain staging dev envs

- src/pages/_assets/examples-content.tsx
> chore: remove dead examples from getting started page

- docs/kratos/passwordless/05_passkeys.mdx
The property was named identifier in an earlier draft of the PR, but has since changed to display_name, and I forgot updating the docs accordingly.
> fix: document passkey identity schema property as display_name

- docs/concepts/personal-access-token.mdx
- src/pages/http-api.js
> docs: update API authorization docs

- .github/workflows/argos.yml
- playwright-argos.config.ts
- tests/playwright-argos/screenshot.css
- tests/playwright-argos/screenshot.spec.ts
> chore: ignore more paths on argos & ignore videos

- docs/kratos/social-signin/15_facebook.mdx
> docs: update facebook guides on email

- docs/kratos/organizations/organizations.mdx
clarify that organizations are only available in Ory Network. 
We can add similar info boxes to most features to clarify what is available where. 
if this looks good to you I would put up a few more PRs.
> fix: organizations notice

- docs/kratos/sdk/05_go.mdx
- docs/kratos/self-hosted/05_go.mdx
- "cooie" in the doc should be "cookie" instead
4. improves the documentation, no issue reference is required.
- [ x I have read the [security policy](../security/policy).
> fix: typo fixing

- docs/kratos/bring-your-own-ui/01_overview.mdx
- docs/kratos/bring-your-own-ui/05_custom-ui-basic-integration.mdx
- docs/kratos/bring-your-own-ui/10_custom-ui-advanced-integration.mdx
- docs/kratos/bring-your-own-ui/15_custom-ui-ory-elements.mdx
- docs/kratos/bring-your-own-ui/20_configure-ory-to-use-your-ui.mdx
This PR makes the custom UI document more readable, removes a bit of fluff and polishes the style.
> chore: simplify custom ui document

- docs/ecosystem/community.md
> fix: community projects and content

- src/theme/ApiWarning.js
- src/theme/DomainWarning.js
> fix: api&domain warning icons

- docs/getting-started/local-development.mdx
In this page it says to use the project_slug https://www.ory.sh/docs/cli/ory-tunnel When I used the project id I encountered weird problems ('Invalid hostname') returned from get-flow sdk function call
> docs: update local-development.mdx

- src/components/ConsoleLink/console-link.tsx
> fix: add workspace paths to the <ConsoleLink /> component

- docs/oathkeeper/guides/websockets.mdx
I added the missing environment variable to ensure the selfservice UI can start correctly. Additionally, I upgraded the Postgres version to avoid the error:
`ERROR: data type uuid has no default operator class for access method "gin" (SQLSTATE 42704)`
This upgrade ensures that `kratos_migrate` works smoothly without encountering issues related to the GIN access method for UUIDs.
> fix: add Missing Env Variable to Kratos Selfservice UI Node and Upgrade Postgres

- docs/console/usage-billing.mdx
> fix: update usage-billing.mdx

- docs/kratos/self-hosted/03_mail-courier-http.mdx
closes https://github.com/ory/kratos/issues/3815
> fix: outdated keys for http courier templates

- code-examples/oathkeeper/ws/Dockerfile
This PR addresses an issue with the websocket container failing to start due to the binary not being executable. The root cause was the dynamic linking of the binary.
Added `CGO_ENABLE=0` to the build process to remove dynamic linking.
> fix: disable CGO in oathkeeper ws

- docs/guides/cli/20_proxy-and-tunnel.mdx
> chore: remove note that Tunnel & Proxy should be used in prod

- docs/self-hosted/oel/quickstart.mdx
> chore: update registry docs

- docs/kratos/manage-identities/25_import-user-accounts-identities.mdx
> fix: typo in use_password_migration_hook

- docs/self-hosted/oel/oauth2/token-prefix.mdx
- src/sidebar.js
> docs: oauth2 token prefixes

- docs/actions/require-verified-address.mdx
- docs/kratos/emails-sms/01_sending-emails-smtp.mdx
> fix: http email courier docs

- docs/identities/sign-in/social-sign-in/redirect-url.mdx
- docs/kratos/organizations/organizations.mdx
> feat: manage organizations and SSO connections through the console

- docs/welcome.mdx
> fix: add Ory Actions to welcome

- docs/welcome.mdx
> chore: indent list

- docs/guides/integrate-with-ory-cloud-through-webhooks.mdx
This adopts the message from the technical adivsory and adds it to the web hook docs.
> feat: document webhook header allow list

- docs/guides/cli/03_cli-migration-v1.mdx
- docs/guides/cli/05_cli-basics.mdx
- docs/guides/gitops.mdx
made a bunch of changes to your PR @zepatrik and refreshed the other CLI doc as well. 
Probably still needs some work to be great but IMHO this is a good start. 
Take a look please and let me know if something needs to be changed and if the migration guide makes sense to you.
> fix: cli migration doc

- docs/kratos/concepts/ui-user-interface.mdx
> fix: remove 404 code examples

- docs/ecosystem/changelog.md
> chore: update newsletter link

- docs/security-compliance/compliance-and-certifications.md
> chore: add trust center link

- docs/kratos/mfa/01_overview.mdx
- **fix: sms to mfa overview**
- **fix: sms to mfa overview**
> fix: sms to mfa overview

- docs/account-experience/index.mdx
> fix: update language list

- docs/kratos/bring-your-own-ui/15_custom-ui-ory-elements.mdx
> chore: fix console page name

- docs/kratos/bring-your-own-ui/20_configure-ory-to-use-your-ui.mdx
> chore: fix console link

- code-examples/migrate-to-ory/1-create-ory-identities.sh
- docs/hydra/guides/client-token-expiration.mdx
- docs/hydra/guides/oauth2-clients.mdx
- docs/hydra/guides/oauth2-webhooks.mdx
- docs/hydra/guides/openid.md
- docs/hydra/jwks.mdx
- docs/identities/session-to-jwt-cors.mdx
- docs/migrate-to-ory/auth0.mdx
- docs/oauth2-oidc/jwt-access-token.mdx
- docs/oauth2-oidc/refresh-token-grant.mdx
Some previously overseen usages.
> fix: update patch Ory CLI commands to be v1 compatible

- docs/kratos/emails-sms/01_sending-emails-smtp.mdx
> fix: sendgrid smtp/http example

- docs/kratos/emails-sms/01_sending-emails-smtp.mdx
Include note about requiring the password to be URI encoded in SMTP connection strings.
> docs: add note about URI encoding password in SMTP string

- docs/guides/custom-domains.mdx
> chore: add caa section

- docs/guides/integrate-with-ory-cloud-through-webhooks.mdx
https://github.com/ory-corp/cloud/pull/6812
> docs: update webhook allow list text

- docs/guides/manage-project-via-api.mdx
The list projects snippet was not correct.
> chore: fix curl command

- docusaurus.config.ts
- package-lock.json
- package.json
> feat: add feedback widget

- docs/kratos/mfa/30_sms.mdx
> docs: update sms and email 2fa docs

- docs/kratos/organizations/organizations.mdx
> chore: refactor organizations docs

- docs/getting-started/integrate-auth/01_go.mdx
- docs/hydra/sdk/05_go.mdx
- docs/keto/sdk/05_go.mdx
- docs/kratos/sdk/05_go.mdx
- src/hooks/index.ts
Closes https://github.com/ory-corp/cloud/issues/4065
> docs: version Go SDK installs

- docs/guides/cli/15_config-identity-service.mdx
- docs/guides/ip-allowlist.mdx
- docs/kratos/bring-your-own-ui/01_overview.mdx
- docs/kratos/mfa/30_sms.mdx
- docs/kratos/passwordless/00_overview.mdx
- docs/kratos/passwordless/06_code.mdx
- docs/kratos/self-service/flows/user-login.mdx
- docs/kratos/self-service/flows/user-registration.mdx
- docs/kratos/social-signin/30_apple.mdx
- docs/troubleshooting/11_actions.mdx
- src/sidebar.ts
fixes issues from https://github.com/ory/docs/pull/1823
> fix: sidebar ids/slugs

- docs/kratos/concepts/security.mdx
- docs/self-hosted/oel/oauth2/migrate.mdx
- src/sidebar.ts
> chore: missing sidebar docs + fixes

- .github/workflows/playwright.yml
> chore: update playwright action

- src/sidebar.ts
- vercel.json
> chore: add sales force to sidebar and redirect twitter guide

- docusaurus.config.ts
- src/plugins/analytics/index.js
> chore: add missing plugin

- docs/kratos/manage-identities/15_customize-identity-schema.mdx
- docs/kratos/self-service/flows/account-recovery-password-reset.mdx
> docs: add passkey to missing places

- docusaurus.config.ts
Doesn't work in dev mode, because the event handler by the external script is executed before the button exists on page. In prod/after build it works.
> chore: add missing link to the footer

- src/sidebar.ts
> chore: fix sidebar migrate guides

- src/plugins/analytics/index.js
> chore: configure auto-block script

- docs/kratos/social-signin/95_account-linking.mdx
> feat: add docs for improved account linking

- src/css/theme.css
> fix: first level

- src/plugins/analytics/index.js
> chore: change blocking map classifications

- docs/ecosystem/upgrading.md
> chore: remove outdated newsletter

- docs/guides/ip-allowlist.mdx
> docs: add ips for Asia region

- src/plugins/analytics/index.js
> chore: allow redocly images through termly

- docs/troubleshooting/40_mandatory-redirect-uri.mdx
This was announced via email to active users. Closes https://github.com/ory-corp/cloud/issues/6586
> docs: add missing advisory

- README.md
- docs/kratos/emails-sms/01_sending-emails-smtp.mdx
- docs/kratos/emails-sms/10_sending-sms.mdx
- src/components/ConsoleLink/console-nav-data.ts
- src/components/ConsoleLink/console-routes.ts
Adds description of SMS in Console
> fix: configure sms in console

- docs/kratos/manage-identities/25_import-user-accounts-identities.mdx
We support importing salted SHA which was missing from docs
> docs: add sha hash support

- docs/kratos/emails-sms/01_sending-emails-smtp.mdx
Adds missing `delivery_strategy` config to SMTP section
> docs: add smtp delivery_strategy

- docs/ecosystem/api-design.md
- src/sidebar.ts
> chore: add missing doc sidebar

- .github/workflows/pm.yml
> feat: add project board automation

- src/sidebar.ts
> fix: add missing docs to sidebar

- docs/kratos/manage-identities/15_customize-identity-schema.mdx
> chore: fix email/phone json schemas

- docs/identities/index.md
> chore: broken link

- docs/guides/rate-limits.mdx
Docs for https://github.com/ory-corp/cloud/pull/7386
> feat: add admin-initiated recovery to rate-limits

- docs/identities/session-to-jwt-cors.mdx
Looks like you need to `base64 -w 0` to make sure the entire base64 string isn't line breaked.
> fix: session to jwt example

- docs/kratos/self-service/flows/user-login.mdx
> chore: add more login methods

- docusaurus.config.ts
> fix: consent url

- docusaurus.config.ts
> fix: add missing consent script

- docusaurus.config.ts
> chore: load consent defer and non-blocking

- docs/kratos/social-signin/15_facebook.mdx
> docs: update example string

- docusaurus.config.ts
Zaraz can be loaded async as it fires a DOM Ready event which we listen for.
> fix: defer init.js

- package-lock.json
- package.json
- src/hooks/index.ts
> feat: use @ory/client-fetch

- docusaurus.config.ts
> fix: require consent for recaptcha

- docusaurus.config.ts
> fix: add missing font variant

- .prettierignore
> chore: add prettier ignore

- docusaurus.config.ts
> fix: async loading of redirect.js

- docusaurus.config.ts
> chore: load kapa.ai through zaraz

- docs/ecosystem/security.md
> chore: research guidelines bug bounty

- src/theme/KapaWidget.tsx
> fix: load kapa only once

- docs/self-hosted/oel/oauth2/upgrade.mdx
> docs: update oel upgrade guide

- docs/guides/ip-allowlist.mdx
> chore: add new egress IP

- docusaurus.config.ts
> feat: new horizontal nav

- docs/hydra/guides/oauth2-webhooks.mdx
Closes https://github.com/ory/hydra/issues/3879
> docs: clarify webhook response payload

- docs/kratos/organizations/organizations.mdx
> docs: document identity pre-provisioning in organization

- docs/hydra/guides/graceful-token-refresh.mdx
> fix: update CLI command to change graceful token refresh

- docs/kratos/concepts/security.mdx
> chore: update docs for CAPTCHAs

- src/sidebar.ts
> chore: duplicate in sidebar

- docs/ecosystem/configuring.md
> docs: fix typo in configuring.md

- docs/troubleshooting/50_account-linking-response-code.mdx
> chore: update technical advisory text

- docs/kratos/quickstart.mdx
Closes https://github.com/ory/hydra/issues/3956
> revert: kratos quickstart checkout command

- src/navbar.ts
- src/sidebar.ts
> docs: add compliance nav

- vercel.json
fixing some redirects for 404 pages.
> chore: redirects for 404 or moved pages

- src/sidebar.ts
> docs: add session management docs to sidebar

- docs/kratos/manage-identities/25_import-user-accounts-identities.mdx
> fix: clarify plain text password import

- docs/migrate-to-ory/auth0.mdx
- src/sidebar.ts
> fix: migrate docs in sidebar

- docs/self-hosted/oel/quickstart.mdx
> chore: correct product name

- docs/hydra/self-hosted/quickstart.mdx
> fix: hydra quickstart

- docs/getting-started/integrate-auth/10_expressjs.mdx
> fix: trailing comma

- docs/hydra/self-hosted/dependencies-environment.md
> chore: mysql version

- docusaurus.config.ts
> fix: consent preferences button

- src/theme/DomainWarning.js
> fix: word order

- docs/identities/sign-in/identifier-first-authentication.mdx
- src/components/ConsoleLink/console-nav-data.ts
https://github.com/ory/docs/issues/2115
I am not sure how to fix the last one
>- the "Enable legacy one-step registration" setting cannot be found in the console registration settings as described in https://www.ory.sh/docs/identities/sign-in/two-step-registration
I assume it is now disable "Enable unified sign up" to get the legacy one-step registration @aeneasr ?
> fix: renamed UI update

- src/css/theme.css
closes https://github.com/ory/docs/issues/2119
> fix: list styles

- docs/kratos/manage-identities/50_scim.mdx
- docs/kratos/reference/jsonnet.mdx
> docs: more detailed SCIM docs

- docs/self-hosted/oel/quickstart.mdx
> docs: fix oel repository path

- docs/kratos/debug/troubleshooting.md
> docs: document ITP quirks

- docs/guides/rate-limits.mdx
> feat: document updated Developer plan rate limits

- docs/self-hosted/deployment.md
> docs: added additional DSN params for Postgres and CockroachDB

- docs/self-hosted/deployment.md
> docs: removed duplicate entry in Standard Pooling section

- docs/kratos/self-hosted/05_go.mdx
ory.FrontendApi changed to ory.FrontendAPI
> docs: update 05_go.mdx

- docs/self-hosted/deployment.md
> docs: high-performance pooling options are only available in OEL images

- docs/kratos/manage-identities/25_import-user-accounts-identities.mdx
Docs for https://github.com/ory/kratos/pull/4390
> feat: password migration hook body customization

- docs/self-hosted/oel/oathkeeper/upgrade-oathkeeper.mdx
> docs: fix oathkeeper versions

- src/sidebar.ts
> chore: simplify sidebar

- docs/actions/live-events.mdx
https://github.com/ory-corp/cloud/issues/7895
Implementation: https://github.com/ory/kratos/pull/4404
> docs: document new events LoginStarted and RegistrationStarted

- docs/actions/live-events.mdx
> fix: update event names that changed during PR review

- docs/actions/live-events.mdx
> fix: add missing event RecoveryInitiatedByAdmin & sort events

- docs/identities/sign-in/actions.mdx
> docs: clarify show_verification_ui action

- docs/self-hosted/deployment.md
> chore: remove note tags

- docs/self-hosted/oel/oauth2/changelog.mdx
> chore: update Hydra OEL changelog

- docs/kratos/social-signin/95_account-linking.mdx
> chore: fix unsupported markdown link

- docs/account-experience/index.mdx
Fixes a broken link (https://github.com/ory/elements/tree/main/src/locales) to supported languages in https://www.ory.sh/docs/account-experience#translations-i18n--message-customization.
> fix: broken link to supported languages in docs

- docs/kratos/emails-sms/05_custom-email-templates.mdx
closes https://github.com/ory-corp/cloud/issues/8129
> fix: clarify email customization only available with custom SMTP

- docs/kratos/self-service/flows/verify-email-account-activation.mdx
> chore: removed TODO

- docs/hydra/guides/graceful-token-refresh.mdx
Feature PR: https://github.com/ory/hydra/pull/3992
> feat: add the count config option for graceful token refresh

- docs/self-hosted/oel/kratos/changelog.mdx
- docs/self-hosted/oel/kratos/upgrade-kratos.mdx
- docs/self-hosted/oel/oauth2/upgrade.mdx
- docs/self-hosted/oel/quickstart.mdx
- src/sidebar.ts
> chore: initials of kratos oel

- docs/polis/guides/examples.mdx
> chore: cleanup

- src/sidebar.ts
> chore: fix OEL headings

- docs/polis/deploy/env-variables.mdx
> chore: retraced UI support will be removed since it is no longer an area of focus

- docs/guides/rate-limits.mdx
> chore: add missing import rate limit for developer plan

- docs/ecosystem/projects.mdx
~- waiting to add the logo here: https://github.com/ory/meta/tree/master/static/logos~ logo is added, lets go 🚀 
> fix: add polis ecosystem

- vercel.json
> chore: missing redirect

- docs/kratos/manage-identities/25_import-user-accounts-identities.mdx
- docs/kratos/social-signin/95_account-linking.mdx
- docs/polis/deploy/env-variables.mdx
> docs: account linking

- src/css/theme.css
> fix: link colors

- docs/ecosystem/sqa.md
> chore: updated source code link for sqa

- docusaurus.config.ts
> chore: dead link

- docusaurus.config.ts
- src/css/theme.css
> fix: styling of cookie preferences button

- docs/actions/live-events.mdx
> chore: add courier live events

- docs/kratos/manage-identities/60_external-id.mdx
- [x ] I confirm that this pull request does not address a security vulnerability. 
> chore: editorial changes

- docs/kratos/manage-identities/60_external-id.mdx
> chore: fixed link

- docs/self-hosted/oel/oel-polis-image-tags.md
- docs/self-hosted/oel/polis/changelog.mdx
- docs/self-hosted/oel/quickstart.mdx
- src/sidebar.ts
Adding barebone skeleton for oel polis to be filled up later with more content.
> chore: skeleton for polis oel

- docs/self-hosted/oel/polis/changelog.mdx
- docs/self-hosted/oel/quickstart.mdx
Updates changelog for polis and fixes quickstart structure.
> chore: update oel structure

- docs/kratos/self-service/flows/user-settings.mdx
Check implemented in https://github.com/ory-corp/cloud/pull/9076
> docs: mention that the new password must be different from the old password

- docs/guides/custom-domains.mdx
> chore: add PSL note for custom domains

- docs/hydra/guides/cors.mdx
- docs/self-hosted/deployment.md
Contributes to https://github.com/ory-corp/cloud/issues/8781, https://github.com/ory-corp/cloud/issues/8800
> feat: rework connection pooling docs

- docs/self-hosted/oel/quickstart.mdx
> chore: oel note
